//! LuaLaTeX booklet rendering (half-letter) of a composed hour. The renderer does no file access:
//! chant scores are found through a caller-supplied [`Chant`] lookup.

use calendar::{Color, Season};
use corpus::lines::{BlockKind, PsalmItem, hymn_rubric_stanza, hymn_rubric_text, parse_block, parse_hymn, parse_psalm};
use corpus::typography::{soften_drop_cap_opening, typeset};
use liturgy::{ElementType, OfficeElement, OfficeHour, OfficeSection, RubricSpan, VoiceRole};

const PREAMBLE: &str = include_str!("preamble.tex");

const MONTHS: [&str; 12] =
    ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];

/// Longest feast name the right-hand running head carries; a longer one gives
/// way to the date so the head stays on one line.
const RUNNING_HEAD_FEAST_MAX: usize = 48;

/// Finds GABC chant scores. `base(category, slug)` returns the path to pass
/// to `\gregorioscore` (the score's path without `.gabc`, which gregoriotex
/// appends) when a score exists; the caller owns every file access.
pub struct Chant<'a> {
    pub base: &'a dyn Fn(&str, &str) -> Option<String>,
}

impl Chant<'_> {
    fn score(&self, category: &str, slug: &str) -> Option<String> {
        if slug.is_empty() {
            return None;
        }
        (self.base)(category, slug).map(|base| format!("\\gregorioscore{{{base}}}\n\n"))
    }
}

/// A complete .tex document for the hour. `chant` is `None` for text only.
pub fn format_office_hour_tex(hour: &OfficeHour, chant: Option<&Chant<'_>>) -> String {
    let mut b = String::new();
    b.push_str(&format!("% Auto-generated by office tex — {} {}\n", hour.hour, hour.date));
    b.push_str(PREAMBLE);
    b.push_str(&document_setup(hour));
    b.push_str("\n\\begin{document}\n\n");
    b.push_str(&title_block(hour));
    for section in &hour.sections {
        b.push_str(&tex_section(section, chant));
    }
    b.push_str("\n\\end{document}\n");
    b
}

fn long_date(hour: &OfficeHour) -> String {
    let d = hour.date;
    format!("{}, {} {}, {:04}", d.weekday().name(), MONTHS[d.month() as usize - 1], d.day(), d.year())
}

/// The running-head names and PDF metadata for this booklet.
fn document_setup(hour: &OfficeHour) -> String {
    let date = long_date(hour);
    let day = if hour.feast.is_empty() || hour.feast.chars().count() > RUNNING_HEAD_FEAST_MAX { &date } else { &hour.feast };
    let mut b = format!("\n\\newcommand{{\\officehour}}{{{}}}\n", tex_line(&hour.hour));
    b.push_str(&format!("\\newcommand{{\\officeday}}{{{}}}\n", tex_line(day)));
    b.push_str(&format!("\\hypersetup{{pdftitle={{{} — {}}}", tex_line(&hour.hour), tex_line(&date)));
    if !hour.feast.is_empty() {
        b.push_str(&format!(",pdfsubject={{{}}}", tex_line(&hour.feast)));
    }
    b.push_str("}\n");
    b
}

fn title_block(hour: &OfficeHour) -> String {
    format!(
        "\\officetitle{{{}}}{{{}}}{{{}}}{{{}}}{{{}}}{{{}}}\n\n",
        tex_line(&hour.hour),
        tex_line(&long_date(hour)),
        tex_line(&hour.feast),
        hour.season.map_or("", season_name),
        hour.color.map_or("", color_name),
        hour.color.map_or("", Color::as_str),
    )
}

/// The season as a printed ordo names it.
fn season_name(season: Season) -> &'static str {
    match season {
        Season::Advent => "Advent",
        Season::Christmas => "Christmastide",
        Season::Epiphany => "Time after Epiphany",
        Season::Septuagesima => "Septuagesima",
        Season::Lent => "Lent",
        Season::Passiontide => "Passiontide",
        Season::Easter => "Eastertide",
        Season::Pentecost => "Time after Pentecost",
    }
}

fn color_name(color: Color) -> &'static str {
    match color {
        Color::White => "White",
        Color::Red => "Red",
        Color::Green => "Green",
        Color::Violet => "Violet",
        Color::Black => "Black",
        Color::Rose => "Rose",
    }
}

fn tex_section(section: &OfficeSection, chant: Option<&Chant<'_>>) -> String {
    let mut b = String::new();
    if !section.label.is_empty() {
        b.push_str(&format!("\\sectionheading{{{}}}\n\n", tex_line(&section.label)));
    }
    for elem in &section.elements {
        b.push_str(&tex_element(elem, chant));
    }
    b
}

fn tex_element(elem: &OfficeElement, chant: Option<&Chant<'_>>) -> String {
    let mut b = String::new();
    match elem.kind {
        ElementType::Rubric => b.push_str(&format_rubric(elem)),
        ElementType::Heading => b.push_str(&format!("\\sectionheading{{{}}}\n\n", tex_line(&elem.text))),
        ElementType::Antiphon => {
            let text = elem.display_text();
            if !text.is_empty() {
                if text.contains('\n') {
                    b.push_str(&format_multiline_antiphon(elem));
                } else {
                    b.push_str(&format!("\\ant{{{}}}\n\n", mediant_line(&text)));
                }
            }
        }
        ElementType::OpeningAcclamation => b.push_str(&format!("\\acclamation{{{}}}\n\n", mediant_line(&elem.text))),
        ElementType::Psalm | ElementType::Canticle => {
            if !elem.label.is_empty() {
                b.push_str(&format!("\n\\psalmlabel{{{}}}{{{}}}\n\n", tex_line(&elem.label), tex_line(&elem.incipit)));
            }
            b.push_str(&format_psalm(&elem.text, &elem.label, elem.kind, chant));
        }
        ElementType::Hymn => {
            if !elem.label.is_empty() {
                b.push_str(&format!("\n\\hymnlabel{{{}}}\n\n", tex_line(&elem.label)));
            }
            b.push_str(&format_hymn(&elem.text, &elem.label, chant));
        }
        ElementType::PsalmDoxology => b.push_str(&format_gloria_patri(&elem.text)),
        ElementType::Prayer | ElementType::Reading => {
            if elem.voice.len() == 1 && !elem.voice[0].spoken && elem.voice[0].text == elem.text {
                b.push_str("{\\color{mutedgray}\n");
                b.push_str(&format_block(&elem.text));
                b.push_str("}\n");
            } else if let Some(turns) = elem.speaker_turns().filter(|t| !t.is_empty()) {
                for turn in turns {
                    let label = turn.role.map_or("", |r| r.label());
                    b.push_str(&format!("\\noindent\\rubric{{\\scshape {label}}}\\par\\nopagebreak\n"));
                    b.push_str(&format_block(&turn.text));
                }
            } else if let Some(voiced) = format_prayer_voice(elem) {
                b.push_str(&voiced);
            } else {
                b.push_str(&format_block(&elem.text));
            }
        }
        ElementType::Doxology
        | ElementType::Versicle
        | ElementType::Response
        | ElementType::Dialogue
        | ElementType::Blessing
        | ElementType::Preces => b.push_str(&format_block(&elem.text)),
        ElementType::Collect => {
            let v = &elem.voice;
            if v.len() == 2 && v[0].spoken && !v[1].spoken && format!("{}{}", v[0].text, v[1].text) == elem.text {
                b.push_str(&format_collect(&v[0].text));
                b.push_str("{\\color{mutedgray}\n");
                b.push_str(&format_block(&v[1].text));
                b.push_str("}\n");
            } else {
                b.push_str(&format_collect(&elem.text));
            }
        }
        ElementType::Chapter => b.push_str(&format_collect(&elem.text)),
        ElementType::ShortResponsory => b.push_str(&format_short_responsory(&elem.text)),
        ElementType::CorporateLordPrayer => b.push_str(&format_corporate_lord_prayer(elem)),
    }
    b
}

fn format_rubric(elem: &OfficeElement) -> String {
    if elem.rubric_spans.is_empty() {
        return format!("\\rubric{{{}}}\n\n", tex_line(&elem.text));
    }
    let mut b = String::from("\\rubric{");
    for RubricSpan { text, prayed } in &elem.rubric_spans {
        if *prayed {
            b.push_str(&format!("\\rubricprayed{{{}}}", tex_line(text)));
        } else {
            b.push_str(&tex_line(text));
        }
    }
    b.push_str("}\n\n");
    b
}

fn format_psalm(text: &str, label: &str, kind: ElementType, chant: Option<&Chant<'_>>) -> String {
    let category = if kind == ElementType::Canticle { "canticles" } else { "psalms" };
    if let Some(score) = chant.and_then(|c| c.score(category, &label_to_slug(label, kind))) {
        return score;
    }
    let psalm = parse_psalm(text);
    let mut b = String::new();
    if !psalm.scripture_ref.is_empty() {
        b.push_str(&format!("{{\\centering\\scriptureref{{{}}}\\par}}\n\n", tex_line(&psalm.scripture_ref)));
    }
    b.push_str("\\begin{psalmverses}\n");
    // The first verse of each block takes the gilt initial; a Gloria never
    // does; a section break re-arms it.
    let mut first_verse = true;
    for item in &psalm.items {
        match item {
            PsalmItem::Section { heading } => {
                b.push_str("\\end{psalmverses}\n");
                b.push_str(&format!("\\canticlesection{{{}}}\n", tex_line(heading)));
                b.push_str("\\begin{psalmverses}\n");
                first_verse = true;
            }
            PsalmItem::Gloria { first, second } => {
                first_verse = false;
                if second.is_empty() {
                    b.push_str(&format!("\\psalmverse{{}}{{{}}}\n", mediant_line(first)));
                } else {
                    b.push_str(&format!("\\gloriapatri{{{}}}{{{}}}\n", mediant_line(first), mediant_line(second)));
                }
            }
            PsalmItem::Verse { number, first, second } => {
                if first_verse {
                    first_verse = false;
                    if number.is_empty() {
                        if second.is_empty() {
                            b.push_str(&format!("\\psalmverse{{}}{{{}}}\n", drop_cap(first)));
                        } else {
                            b.push_str(&format!("\\psalmverse{{}}{{{}\\mediant{{}}{}}}\n", drop_cap(first), tex_line(second)));
                        }
                        continue;
                    }
                }
                if second.is_empty() {
                    b.push_str(&format!("\\psalmverse{{{number}}}{{{}}}\n", tex_line(first)));
                } else {
                    b.push_str(&format!("\\psalmverse{{{number}}}{{{}\\mediant{{}}{}}}\n", tex_line(first), tex_line(second)));
                }
            }
        }
    }
    b.push_str("\\end{psalmverses}\n\n");
    b
}

fn format_hymn(text: &str, label: &str, chant: Option<&Chant<'_>>) -> String {
    if let Some(score) = chant.and_then(|c| c.score("hymns", &label_to_slug(label, ElementType::Hymn))) {
        return score;
    }
    let hymn = parse_hymn(text);
    let mut b = String::new();
    if !hymn.title.is_empty() {
        match hymn_rubric_text(&hymn.title) {
            Some(rubric) => b.push_str(&format!("{{\\centering\\rubric{{{}}}\\par}}\n\n", tex_line(rubric))),
            None => b.push_str(&format!("\\hymnlabel{{{}}}\n\n", tex_line(&hymn.title))),
        }
    }
    b.push_str("\\begin{hymnverses}\n");
    let mut dropped = false;
    for stanza in &hymn.stanzas {
        if let Some(rubrics) = hymn_rubric_stanza(stanza) {
            for rubric in rubrics {
                b.push_str(&format!("{{\\centering\\rubric{{{}}}\\par}}\\smallskip\n", tex_line(rubric)));
            }
            continue;
        }
        if dropped {
            b.push_str("\\noindent ");
        }
        for (i, line) in stanza.iter().enumerate() {
            if i > 0 {
                b.push_str("\\\\\n");
            }
            if !dropped && i == 0 {
                b.push_str(&drop_cap(line));
                dropped = true;
            } else {
                b.push_str(&tex_line(line));
            }
        }
        b.push_str("\\par\\capclear\\smallskip\n");
    }
    b.push_str("\\end{hymnverses}\n\n");
    b
}

/// A multi-line antiphon (a Marian antiphon): the anthem in italics, then any
/// versicle and collect as a block.
fn format_multiline_antiphon(elem: &OfficeElement) -> String {
    let mut b = String::new();
    if !elem.label.is_empty() {
        b.push_str(&format!("\n\\hymnlabel{{{}}}\n\n", tex_line(&elem.label)));
    }
    let (anthem, rest) = elem.text.split_once("\n\n").unwrap_or((&elem.text, ""));
    let lines: Vec<&str> = anthem.split('\n').map(str::trim).filter(|l| !l.is_empty()).collect();
    if let Some((first, more)) = lines.split_first() {
        b.push_str("{\\itshape ");
        b.push_str(&drop_cap(first));
        if !more.is_empty() {
            b.push(' ');
            b.push_str(&more.iter().map(|l| mediant_line(l)).collect::<Vec<_>>().join(" "));
        }
        b.push_str("}\\par\\capclear\n");
    }
    let rest = rest.trim();
    if rest.is_empty() {
        b.push('\n');
    } else {
        b.push_str("\\smallskip\n");
        b.push_str(&format_block(rest));
    }
    b
}

fn format_short_responsory(text: &str) -> String {
    let mut b = String::new();
    let lines = parse_block(text);
    // A responsory that opens on its versicle (Compline's "Keep us, O Lord")
    // takes no initial.
    let mut first_response = lines.iter().find(|l| l.kind != BlockKind::Gap).is_some_and(|l| l.kind == BlockKind::Response);
    let mut prose: Vec<String> = Vec::new();
    let flush = |b: &mut String, prose: &mut Vec<String>| {
        if !prose.is_empty() {
            b.push_str(&format!("\\noindent {}\\par\n", prose.join(" ")));
            prose.clear();
        }
    };
    for line in lines {
        match line.kind {
            BlockKind::Gap => {
                flush(&mut b, &mut prose);
                b.push_str("\\smallskip\n");
            }
            BlockKind::Response => {
                flush(&mut b, &mut prose);
                if first_response {
                    let (initial, word_rest, tail) = split_drop_cap(&typeset(&soften_drop_cap_opening(&line.text)));
                    b.push_str(&format!(
                        "\\shortresponse{{{}}}{{{}}}{}\\par\\capclear\n",
                        tex_line(&initial),
                        tex_line(&word_rest),
                        mediant_line(&tail)
                    ));
                    first_response = false;
                } else {
                    b.push_str(&format!("\\response{{{}}}\n", mediant_line(&line.text)));
                }
            }
            BlockKind::Versicle => {
                flush(&mut b, &mut prose);
                b.push_str(&format!("\\versicle{{{}}}\n", mediant_line(&line.text)));
            }
            BlockKind::All => {
                flush(&mut b, &mut prose);
                b.push_str(&format!("\\noindent\\allsig{{}}{}\\par\n", mediant_line(&line.text)));
            }
            BlockKind::Blessing => {
                flush(&mut b, &mut prose);
                b.push_str(&format!("\\noindent\\blessingsig{{}}{}\\par\n", mediant_line(&line.text)));
            }
            BlockKind::ScriptureRef => {
                flush(&mut b, &mut prose);
                b.push_str(&format!("{{\\centering\\scriptureref{{{}}}\\par}}\n", tex_line(&line.text)));
            }
            BlockKind::Prose => prose.push(mediant_line(&line.text)),
        }
    }
    flush(&mut b, &mut prose);
    b.push('\n');
    b
}

fn drop_cap(text: &str) -> String {
    let (initial, word_rest, tail) = split_drop_cap(&typeset(&soften_drop_cap_opening(text)));
    if initial.is_empty() {
        return tex_line(text);
    }
    format!("\\dropcap{{{}}}{{{}}}{}", tex_line(&initial), tex_line(&word_rest), mediant_line(&tail))
}

/// The initial, the rest of the opening word, and the remainder. Opening
/// punctuation (a quote or apostrophe) joins the initial, as ::first-letter
/// takes it on the web.
fn split_drop_cap(text: &str) -> (String, String, String) {
    let lead = text.find(|c: char| c.is_alphanumeric() || c.is_whitespace()).unwrap_or(text.len());
    let Some(first) = text[lead..].chars().next().filter(|c| c.is_alphanumeric()) else {
        return match text.chars().next() {
            Some(c) => split_at_word(text, c.len_utf8()),
            None => (String::new(), String::new(), String::new()),
        };
    };
    split_at_word(text, lead + first.len_utf8())
}

fn split_at_word(text: &str, initial_end: usize) -> (String, String, String) {
    let (initial, rest) = text.split_at(initial_end);
    let word_end = rest.find(char::is_whitespace).unwrap_or(rest.len());
    (initial.to_string(), rest[..word_end].to_string(), rest[word_end..].to_string())
}

fn format_corporate_lord_prayer(elem: &OfficeElement) -> String {
    let (mut officiant, mut response) = (String::new(), String::new());
    for span in &elem.voice {
        match span.role {
            Some(VoiceRole::Officiant) => officiant.push_str(&span.text),
            Some(VoiceRole::Response) => response.push_str(&span.text),
            Some(VoiceRole::Priest | VoiceRole::All) | None => {}
        }
    }
    if officiant.is_empty() || response.is_empty() {
        return format_block(&elem.text);
    }
    let flow = |s: &str| s.split_whitespace().collect::<Vec<_>>().join(" ");
    format!("{}\\par\\capclear\n\\response{{{}}}\n\n", drop_cap(&flow(&officiant)), mediant_line(&flow(&response)))
}

fn format_collect(text: &str) -> String {
    format_block_with_opening(text, true)
}

fn format_block(text: &str) -> String {
    format_block_with_opening(text, false)
}

/// Versicles, responses, prayers, chapters, blessings, preces: hard-wrapped
/// prose lines flow into paragraphs; blank lines break them.
fn format_block_with_opening(text: &str, opening_drop_cap: bool) -> String {
    let mut b = String::new();
    let mut prose: Vec<String> = Vec::new();
    let mut dropped = false;
    let flush = |b: &mut String, prose: &mut Vec<String>, dropped: &mut bool| {
        if prose.is_empty() {
            return;
        }
        if opening_drop_cap && !*dropped {
            b.push_str(&drop_cap(&prose[0]));
            if prose.len() > 1 {
                b.push(' ');
                b.push_str(&prose[1..].iter().map(|l| mediant_line(l)).collect::<Vec<_>>().join(" "));
            }
            *dropped = true;
            b.push_str("\\par\\capclear\n");
        } else {
            b.push_str("\\noindent ");
            b.push_str(&prose.iter().map(|l| mediant_line(l)).collect::<Vec<_>>().join(" "));
            b.push_str("\\par\n");
        }
        prose.clear();
    };
    for line in parse_block(text) {
        let sigil = match line.kind {
            BlockKind::Gap => {
                flush(&mut b, &mut prose, &mut dropped);
                b.push_str("\\smallskip\n");
                continue;
            }
            BlockKind::ScriptureRef => {
                flush(&mut b, &mut prose, &mut dropped);
                b.push_str(&format!("{{\\centering\\scriptureref{{{}}}\\par}}\n", tex_line(&line.text)));
                continue;
            }
            BlockKind::Versicle => {
                flush(&mut b, &mut prose, &mut dropped);
                b.push_str(&format!("\\versicle{{{}}}\n", mediant_line(&line.text)));
                continue;
            }
            BlockKind::Response => {
                flush(&mut b, &mut prose, &mut dropped);
                b.push_str(&format!("\\response{{{}}}\n", mediant_line(&line.text)));
                continue;
            }
            BlockKind::Blessing => "\\blessingsig{}",
            BlockKind::All => "\\allsig{}",
            BlockKind::Prose => {
                prose.push(line.text);
                continue;
            }
        };
        flush(&mut b, &mut prose, &mut dropped);
        b.push_str(&format!("\\noindent{sigil}{}\\par\n", mediant_line(&line.text)));
    }
    flush(&mut b, &mut prose, &mut dropped);
    b.push('\n');
    b
}

fn format_gloria_patri(text: &str) -> String {
    let lines: Vec<&str> = text.split('\n').collect();
    let (line1, line2) = if lines.len() >= 2 { (lines[0].trim(), lines[1].trim()) } else { (text.trim(), "") };
    if line2.is_empty() {
        format!("\\noindent {}\\par\n\n", mediant_line(line1))
    } else {
        format!("\\gloriapatri{{{}}}{{{}}}\n\n", mediant_line(line1), mediant_line(line2))
    }
}

/// Escapes a line, setting a " * " pointing mediant as `\mediant{}`.
fn mediant_line(s: &str) -> String {
    let s = &typeset(s);
    match s.split_once(" * ") {
        Some((before, after)) => format!("{}\\mediant{{}}{}", tex_line(before), tex_line(after)),
        None => match s.strip_suffix(" *") {
            Some(before) => format!("{}\\mediant{{}}", tex_line(before)),
            None => tex_line(s),
        },
    }
}

/// Escapes the LaTeX special characters.
pub fn escape_tex(s: &str) -> String {
    let mut b = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '\\' => b.push_str("\\textbackslash{}"),
            '&' => b.push_str("\\&"),
            '%' => b.push_str("\\%"),
            '$' => b.push_str("\\$"),
            '#' => b.push_str("\\#"),
            '_' => b.push_str("\\_"),
            '{' => b.push_str("\\{"),
            '}' => b.push_str("\\}"),
            '~' => b.push_str("\\textasciitilde{}"),
            '^' => b.push_str("\\textasciicircum{}"),
            c => b.push(c),
        }
    }
    b
}

fn tex_line(s: &str) -> String {
    escape_tex(&typeset(s)).replace('✠', "\\crux{}")
}

/// The GABC slug of an element label: "Psalm 67" → "067", else a slug.
pub fn label_to_slug(label: &str, kind: ElementType) -> String {
    if label.is_empty() {
        return String::new();
    }
    if kind == ElementType::Psalm
        && let Some(after) = label.strip_prefix("Psalm ")
    {
        let num = after.split_whitespace().next().unwrap_or("");
        return format!("{num:0>3}");
    }
    slugify(label)
}

fn slugify(s: &str) -> String {
    let mut b = String::new();
    let mut prev_sep = false;
    for c in s.to_lowercase().chars() {
        if c.is_alphabetic() || c.is_numeric() {
            b.push(c);
            prev_sep = false;
        } else if !prev_sep && !b.is_empty() {
            b.push('-');
            prev_sep = true;
        }
    }
    b.trim_end_matches('-').to_string()
}

/// Spoken/silent transitions inside a plain prayer; `None` for role-bearing
/// or invalid partitions.
fn format_prayer_voice(elem: &OfficeElement) -> Option<String> {
    let mut joined = String::new();
    let mut silent = false;
    for span in &elem.voice {
        if span.role.is_some() {
            return None;
        }
        joined.push_str(&span.text);
        silent = silent || !span.spoken;
    }
    if !silent || joined != elem.text {
        return None;
    }
    let mut b = String::from("\\noindent ");
    for span in &elem.voice {
        let mut text = span.text.as_str();
        if !span.spoken {
            // \color ends with \ignorespaces: a leading space stays outside it.
            let trimmed = text.trim_start();
            if trimmed.len() < text.len() {
                b.push(' ');
            }
            b.push_str("{\\color{mutedgray}");
            text = trimmed;
        }
        for (i, paragraph) in text.split("\n\n").enumerate() {
            if i > 0 {
                b.push_str("\\par\n\\noindent ");
            }
            b.push_str(&mediant_line(&paragraph.replace('\n', " ")));
        }
        if !span.spoken {
            b.push('}');
        }
    }
    b.push_str("\\par\n\n");
    Some(b)
}

#[cfg(test)]
mod tests {
    use super::*;
    use calendar::Date;
    use liturgy::{PrayerForm, VoiceSpan};

    const PSALM_67: &str = "Psalm 67\n\nGOD be merciful unto us, and bless us * and shew us the light of his countenance:\n2. That thy way may be known upon earth * thy saving health among all nations.\nGlory be to the Father, and to the Son, and to the Holy Ghost;\nas it was in the beginning, is now, and ever shall be, world without end. Amen.\n";

    #[test]
    fn escaping() {
        for (input, want) in [
            ("hello", "hello"),
            ("a & b", "a \\& b"),
            ("100%", "100\\%"),
            ("$10", "\\$10"),
            ("#1", "\\#1"),
            ("a_b", "a\\_b"),
            ("{x}", "\\{x\\}"),
            ("~tilde", "\\textasciitilde{}tilde"),
            ("a^b", "a\\textasciicircum{}b"),
            ("back\\slash", "back\\textbackslash{}slash"),
            ("a & b % c", "a \\& b \\% c"),
        ] {
            assert_eq!(escape_tex(input), want, "{input}");
        }
        assert_eq!(tex_line("May the Lord ✠ bless us."), "May the Lord \\crux{} bless us.");
        assert_eq!(tex_line("God & ✠"), "God \\& \\crux{}");
        assert_eq!(mediant_line("God be * merciful"), "God be\\mediant{}merciful");
        assert_eq!(mediant_line("Hail *"), "Hail\\mediant{}");
    }

    #[test]
    fn slugs() {
        for (input, want) in
            [("Benedictus", "benedictus"), ("Nunc Dimittis", "nunc-dimittis"), ("hello-world", "hello-world"), ("  spaces  ", "spaces")]
        {
            assert_eq!(slugify(input), want);
        }
        for (label, kind, want) in [
            ("Psalm 67", ElementType::Psalm, "067"),
            ("Psalm 4", ElementType::Psalm, "004"),
            ("Psalm 118 (Aleph)", ElementType::Psalm, "118"),
            ("Magnificat", ElementType::Canticle, "magnificat"),
            ("Aeterne Rerum Conditor", ElementType::Hymn, "aeterne-rerum-conditor"),
            ("", ElementType::Hymn, ""),
        ] {
            assert_eq!(label_to_slug(label, kind), want);
        }
    }

    #[test]
    fn display_text_is_typeset() {
        assert_eq!(tex_line("Luke 1:68-79"), "Luke 1:68–79");
        assert_eq!(tex_line(r#"He said, "Peace be unto you.""#), "He said, “Peace be unto you.”");
        assert_eq!(tex_line("'Tis Aaron's beard & more"), "’Tis Aaron’s beard \\& more");
        // A pointed line is typeset whole, so a quote after the mediant still closes.
        assert_eq!(mediant_line("and said, 'Peace * be with you.'"), "and said, ‘Peace\\mediant{}be with you.’");
        // Opening punctuation joins the initial, as ::first-letter takes it on the web.
        assert_eq!(drop_cap("'Twas the Lord's doing"), "\\dropcap{’T}{was} the Lord’s doing");
    }

    #[test]
    fn versicles_and_responses_take_the_sigil_gutter() {
        let got = format_block("V. O Lord, open thou our lips.\nR. And our mouth * shall shew forth thy praise.\nAll: Amen.");
        assert!(got.contains("\\versicle{O Lord, open thou our lips.}\n"), "{got}");
        assert!(got.contains("\\response{And our mouth\\mediant{}shall shew forth thy praise.}\n"), "{got}");
        assert!(got.contains("\\noindent\\allsig{}Amen.\\par"), "{got}");
    }

    #[test]
    fn short_responsory_initial_only_on_an_opening_response() {
        let opening =
            format_short_responsory("R. Incline my heart * unto thy testimonies.\nV. Turn away mine eyes.\nR. Unto thy testimonies.");
        assert!(opening.starts_with("\\shortresponse{I}{ncline} my heart\\mediant{}unto thy testimonies.\\par\\capclear\n"), "{opening}");
        assert!(opening.contains("\\versicle{Turn away mine eyes.}") && opening.contains("\\response{Unto thy testimonies.}"));

        let versicle_first =
            format_short_responsory("V. Keep us, O Lord, as the apple of an eye.\nR. Hide us under the shadow of thy wings.");
        assert!(!versicle_first.contains("\\shortresponse"), "{versicle_first}");
        assert!(versicle_first.contains("\\response{Hide us under the shadow of thy wings.}"), "{versicle_first}");
    }

    #[test]
    fn drop_cap_paragraphs_clear_their_initial() {
        assert!(format_collect("Almighty God, who art.\n").contains("\\dropcap{A}{lmighty} God, who art.\\par\\capclear\n"));
        let hymn = format_hymn("O Framer of the earth and sky,\nRuler of all things.\n\nSecond stanza here.\n", "", None);
        assert_eq!(hymn.matches("\\capclear").count(), 2, "{hymn}");
    }

    #[test]
    fn secret_span_keeps_its_leading_space_outside_the_colour() {
        let mut elem = OfficeElement::new(ElementType::Prayer, "I believe in God the Father Almighty.");
        elem.voice = vec![VoiceSpan::new("I believe", true, None), VoiceSpan::new(" in God the Father Almighty.", false, None)];
        let got = format_prayer_voice(&elem).expect("voiced");
        assert_eq!(got, "\\noindent I believe {\\color{mutedgray}in God the Father Almighty.}\\par\n\n");
    }

    #[test]
    fn title_and_running_heads() {
        let mut hour = OfficeHour {
            form: PrayerForm::Private,
            date: Date::new(2026, 9, 29),
            hour: "Lauds".into(),
            title: String::new(),
            season: Some(Season::Pentecost),
            feast: "Dedication of St Michael the Archangel".into(),
            color: Some(Color::White),
            sections: vec![],
            decisions: vec![],
        };
        assert_eq!(
            title_block(&hour),
            "\\officetitle{Lauds}{Tuesday, September 29, 2026}{Dedication of St Michael the Archangel}{Time after Pentecost}{White}{white}\n\n"
        );
        let setup = document_setup(&hour);
        assert!(setup.contains("\\newcommand{\\officeday}{Dedication of St Michael the Archangel}"), "{setup}");
        assert!(setup.contains("pdftitle={Lauds — Tuesday, September 29, 2026},pdfsubject={Dedication of St Michael the Archangel}"));

        hour.feast = "Saturday of Our Lady, with a Commemoration of the Holy Martyrs".into();
        assert!(document_setup(&hour).contains("\\newcommand{\\officeday}{Tuesday, September 29, 2026}"));
        hour.feast.clear();
        (hour.season, hour.color) = (None, None);
        assert_eq!(title_block(&hour), "\\officetitle{Lauds}{Tuesday, September 29, 2026}{}{}{}{}\n\n");
        assert!(!document_setup(&hour).contains("pdfsubject"));
    }

    #[test]
    fn drop_cap_boxes_only_the_first_word() {
        for (text, parts, tex) in [
            ("", ("", "", ""), ""),
            ("O", ("O", "", ""), "\\dropcap{O}{}"),
            ("Almighty God", ("A", "lmighty", " God"), "\\dropcap{A}{lmighty} God"),
            ("O God", ("O", "", " God"), "\\dropcap{O}{} God"),
            ("O\u{a0}God", ("O", "", "\u{a0}God"), "\\dropcap{O}{}\u{a0}God"),
            ("God * save us", ("G", "od", " * save us"), "\\dropcap{G}{od}\\mediant{}save us"),
        ] {
            let (a, b, c) = split_drop_cap(text);
            assert_eq!((a.as_str(), b.as_str(), c.as_str()), parts, "{text:?}");
            assert_eq!(drop_cap(text), tex);
        }
    }

    #[test]
    fn psalm_opening_takes_one_softened_initial() {
        let got = format_psalm(PSALM_67, "Psalm 67", ElementType::Psalm, None);
        assert!(got.contains("\\psalmverse{}{\\dropcap{G}{od} be merciful unto us, and bless us\\mediant{}and shew us"), "{got}");
        assert_eq!(got.matches("\\dropcap{").count(), 1);
        assert!(got.contains("\\psalmverse{2}") && got.contains("\\gloriapatri{"));

        let numbered = format_psalm("2. That thy way may be known * among all nations.\n", "Psalm 67", ElementType::Psalm, None);
        assert!(!numbered.contains("\\dropcap{"), "{numbered}");

        let sectioned = format_psalm(
            "Canticle\n\nFirst opening * alpha.\n\n[section: Part II]\n\nSECOND opening * beta.\n",
            "Canticle",
            ElementType::Canticle,
            None,
        );
        assert_eq!(sectioned.matches("\\dropcap{").count(), 2, "{sectioned}");
        assert!(sectioned.contains("\\canticlesection{Part II}") && sectioned.contains("\\dropcap{S}{econd} opening"));
    }

    #[test]
    fn chant_scores_replace_text_only_when_found() {
        let base = |category: &str, slug: &str| (category == "psalms" && slug == "067").then(|| "data/texts/chant/psalms/067".to_string());
        let chant = Chant { base: &base };
        let got = format_psalm(PSALM_67, "Psalm 67", ElementType::Psalm, Some(&chant));
        assert_eq!(got, "\\gregorioscore{data/texts/chant/psalms/067}\n\n");
        let missing = format_psalm(PSALM_67, "Psalm 68", ElementType::Psalm, Some(&chant));
        assert!(missing.contains("\\psalmverse"));

        let hymn = "Aeterne rerum conditor\n\nO Framer of the earth and sky,\nRuler of all things high and low.\n";
        let text = format_hymn(hymn, "Aeterne Rerum Conditor", Some(&chant));
        assert!(text.contains("\\dropcap{O}{} Framer"), "{text}");
    }

    #[test]
    fn multiline_antiphon_flows_the_anthem() {
        let mut elem = OfficeElement::new(
            ElementType::Antiphon,
            "Hail, holy Queen, Mother of mercy,\nour life, our sweetness, and our hope.\n\nV. Pray for us, O holy Mother of God.\nR. That we may be made worthy of the promises of Christ.",
        );
        elem.label = "Salve Regina".into();
        let got = format_multiline_antiphon(&elem);
        assert!(got.contains("\\hymnlabel{Salve Regina}"));
        assert!(
            got.contains(
                "{\\itshape \\dropcap{H}{ail,} holy Queen, Mother of mercy, our life, our sweetness, and our hope.}\\par\\capclear"
            ),
            "{got}"
        );
        assert!(got.contains("\\versicle{") && got.contains("\\response{"));

        let only =
            format_multiline_antiphon(&OfficeElement::new(ElementType::Antiphon, "Line one of the anthem,\nline two of the anthem."));
        assert!(only.contains("{\\itshape \\dropcap{L}{ine} one of the anthem, line two of the anthem.}"), "{only}");
    }

    #[test]
    fn gloria_patri() {
        let got = format_gloria_patri("Glory be to the Father;\nas it was in the beginning.");
        assert_eq!(got, "\\gloriapatri{Glory be to the Father;}{as it was in the beginning.}\n\n");
        assert_eq!(format_gloria_patri("Glory be"), "\\noindent Glory be\\par\n\n");
    }
}
