//! LuaLaTeX booklet rendering (half-letter) of a composed hour. Ported from
//! Go's `output/tex.go`. The renderer does no file access: chant scores are
//! found through a caller-supplied [`Chant`] lookup.

use corpus::lines::{BlockKind, PsalmItem, hymn_rubric_stanza, hymn_rubric_text, parse_block, parse_hymn, parse_psalm};
use liturgy::{ElementType, OfficeElement, OfficeHour, OfficeSection, RubricSpan, VoiceRole};

const PREAMBLE: &str = include_str!("preamble.tex");

const MONTHS: [&str; 12] =
    ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];

/// Finds GABC chant scores. `base(category, slug)` returns the path to pass
/// to `\gregorioscore` (the score's path without `.gabc`, which gregoriotex
/// appends) when a score exists; the caller owns every file access.
pub struct Chant<'a> {
    pub base: &'a dyn Fn(&str, &str) -> Option<String>,
}

impl Chant<'_> {
    fn score(&self, category: &str, slug: &str) -> Option<String> {
        if slug.is_empty() {
            return None;
        }
        (self.base)(category, slug).map(|base| format!("\\gregorioscore{{{base}}}\n\n"))
    }
}

/// A complete .tex document for the hour. `chant` is `None` for text only.
pub fn format_office_hour_tex(hour: &OfficeHour, chant: Option<&Chant<'_>>) -> String {
    let mut b = String::new();
    b.push_str(&format!("% Auto-generated by office tex — {} {}\n", hour.hour, hour.date));
    b.push_str(PREAMBLE);
    b.push_str(&title_block(hour));
    for section in &hour.sections {
        b.push_str(&tex_section(section, chant));
    }
    b.push_str("\n\\end{document}\n");
    b
}

fn title_block(hour: &OfficeHour) -> String {
    let d = hour.date;
    let date = format!("{}, {} {}, {:04}", d.weekday().name(), MONTHS[d.month() as usize - 1], d.day(), d.year());
    let mut b = String::from("\\begin{center}\n");
    b.push_str("  {\\color{goldline}\\rule{\\linewidth}{0.6pt}}\\\\[1pt]\n");
    b.push_str("  {\\color{goldline}\\rule{\\linewidth}{0.6pt}}\\\\[6pt]\n");
    b.push_str(&format!("  {{\\Large\\scshape The Order for {}}}\\\\[4pt]\n", escape_tex(&hour.hour)));
    b.push_str(&format!("  {{\\normalsize {}}}\\\\[2pt]\n", escape_tex(&date)));
    if !hour.feast.is_empty() {
        b.push_str(&format!("  {{\\normalsize\\itshape {}}}\\\\[2pt]\n", escape_tex(&hour.feast)));
    }
    b.push_str(&format!(
        "  {{\\small\\color{{mutedgray}}Season: {} \\quad$\\cdot$\\quad Color: {}}}\\\\[6pt]\n",
        escape_tex(hour.season.map_or("", |s| s.as_str())),
        escape_tex(hour.color.map_or("", |c| c.as_str()))
    ));
    b.push_str("  {\\color{goldline}\\rule{\\linewidth}{0.6pt}}\\\\[1pt]\n");
    b.push_str("  {\\color{goldline}\\rule{\\linewidth}{0.6pt}}\\\\[4pt]\n");
    b.push_str("  {\\color{ornamentgold}\\small$\\diamond$}\n");
    b.push_str("\\end{center}\n\n");
    b
}

fn tex_section(section: &OfficeSection, chant: Option<&Chant<'_>>) -> String {
    let mut b = String::new();
    if !section.label.is_empty() {
        b.push_str(&format!("\\sectionheading{{{}}}\n\n", escape_tex(&section.label)));
    }
    for elem in &section.elements {
        b.push_str(&tex_element(elem, chant));
    }
    b
}

fn tex_element(elem: &OfficeElement, chant: Option<&Chant<'_>>) -> String {
    let mut b = String::new();
    match elem.kind {
        ElementType::Rubric => b.push_str(&format_rubric(elem)),
        ElementType::Heading => b.push_str(&format!("\\sectionheading{{{}}}\n\n", escape_tex(&elem.text))),
        ElementType::Antiphon => {
            let text = elem.display_text();
            if !text.is_empty() {
                if text.contains('\n') {
                    b.push_str(&format_multiline_antiphon(elem));
                } else {
                    b.push_str(&format!("\\ant{{{}}}\n\n", mediant_line(&text)));
                }
            }
        }
        ElementType::OpeningAcclamation => b.push_str(&format!("\\acclamation{{{}}}\n\n", mediant_line(&elem.text))),
        ElementType::Psalm | ElementType::Canticle => {
            if !elem.label.is_empty() {
                b.push_str(&format!("\n\\psalmlabel{{{}}}{{{}}}\n\n", escape_tex(&elem.label), escape_tex(&elem.incipit)));
            }
            b.push_str(&format_psalm(&elem.text, &elem.label, elem.kind, chant));
        }
        ElementType::Hymn => {
            if !elem.label.is_empty() {
                b.push_str(&format!("\n\\begin{{center}}{{\\small\\itshape {}}}\\end{{center}}\n\n", escape_tex(&elem.label)));
            }
            b.push_str(&format_hymn(&elem.text, &elem.label, chant));
        }
        ElementType::PsalmDoxology => b.push_str(&format_gloria_patri(&elem.text)),
        ElementType::Prayer | ElementType::Reading => {
            if elem.voice.len() == 1 && !elem.voice[0].spoken && elem.voice[0].text == elem.text {
                b.push_str("{\\color{mutedgray}\n");
                b.push_str(&format_block(&elem.text));
                b.push_str("}\n");
            } else if let Some(turns) = elem.speaker_turns().filter(|t| !t.is_empty()) {
                for turn in turns {
                    let label = turn.role.map_or("", |r| r.label());
                    b.push_str(&format!("\\noindent\\rubric{{\\scshape {label}}}\\par\\nopagebreak\n"));
                    b.push_str(&format_block(&turn.text));
                }
            } else if let Some(voiced) = format_prayer_voice(elem) {
                b.push_str(&voiced);
            } else {
                b.push_str(&format_block(&elem.text));
            }
        }
        ElementType::Doxology
        | ElementType::Versicle
        | ElementType::Response
        | ElementType::Dialogue
        | ElementType::Blessing
        | ElementType::Preces => b.push_str(&format_block(&elem.text)),
        ElementType::Collect => {
            let v = &elem.voice;
            if v.len() == 2 && v[0].spoken && !v[1].spoken && format!("{}{}", v[0].text, v[1].text) == elem.text {
                b.push_str(&format_collect(&v[0].text));
                b.push_str("{\\color{mutedgray}\n");
                b.push_str(&format_block(&v[1].text));
                b.push_str("}\n");
            } else {
                b.push_str(&format_collect(&elem.text));
            }
        }
        ElementType::Chapter => b.push_str(&format_collect(&elem.text)),
        ElementType::ShortResponsory => b.push_str(&format_short_responsory(&elem.text)),
        ElementType::CorporateLordPrayer => b.push_str(&format_corporate_lord_prayer(elem)),
    }
    b
}

fn format_rubric(elem: &OfficeElement) -> String {
    if elem.rubric_spans.is_empty() {
        return format!("\\rubric{{{}}}\n\n", escape_tex(&elem.text));
    }
    let mut b = String::from("\\rubric{");
    for RubricSpan { text, prayed } in &elem.rubric_spans {
        if *prayed {
            b.push_str(&format!("\\rubricprayed{{{}}}", tex_line(text)));
        } else {
            b.push_str(&escape_tex(text));
        }
    }
    b.push_str("}\n\n");
    b
}

fn format_psalm(text: &str, label: &str, kind: ElementType, chant: Option<&Chant<'_>>) -> String {
    let category = if kind == ElementType::Canticle { "canticles" } else { "psalms" };
    if let Some(score) = chant.and_then(|c| c.score(category, &label_to_slug(label, kind))) {
        return score;
    }
    let psalm = parse_psalm(text);
    let mut b = String::new();
    if !psalm.scripture_ref.is_empty() {
        b.push_str(&format!("{{\\centering\\scriptureref{{{}}}\\par}}\n\n", escape_tex(&psalm.scripture_ref)));
    }
    b.push_str("\\begin{psalmverses}\n");
    // The first verse of each block takes the gilt initial; a Gloria never
    // does; a section break re-arms it.
    let mut first_verse = true;
    for item in &psalm.items {
        match item {
            PsalmItem::Section { heading } => {
                b.push_str("\\end{psalmverses}\n");
                b.push_str(&format!("\\canticlesection{{{}}}\n", escape_tex(heading)));
                b.push_str("\\begin{psalmverses}\n");
                first_verse = true;
            }
            PsalmItem::Gloria { first, second } => {
                first_verse = false;
                if second.is_empty() {
                    b.push_str(&format!("\\psalmverse{{}}{{{}}}\n", mediant_line(first)));
                } else {
                    b.push_str(&format!("\\gloriapatri{{{}}}{{{}}}\n", mediant_line(first), mediant_line(second)));
                }
            }
            PsalmItem::Verse { number, first, second } => {
                if first_verse {
                    first_verse = false;
                    if number.is_empty() {
                        if second.is_empty() {
                            b.push_str(&format!("\\psalmverse{{}}{{{}}}\n", drop_cap(first)));
                        } else {
                            b.push_str(&format!("\\psalmverse{{}}{{{}\\mediant{{}}{}}}\n", drop_cap(first), tex_line(second)));
                        }
                        continue;
                    }
                }
                if second.is_empty() {
                    b.push_str(&format!("\\psalmverse{{{number}}}{{{}}}\n", tex_line(first)));
                } else {
                    b.push_str(&format!("\\psalmverse{{{number}}}{{{}\\mediant{{}}{}}}\n", tex_line(first), tex_line(second)));
                }
            }
        }
    }
    b.push_str("\\end{psalmverses}\n\n");
    b
}

fn format_hymn(text: &str, label: &str, chant: Option<&Chant<'_>>) -> String {
    if let Some(score) = chant.and_then(|c| c.score("hymns", &label_to_slug(label, ElementType::Hymn))) {
        return score;
    }
    let hymn = parse_hymn(text);
    let mut b = String::new();
    if !hymn.title.is_empty() {
        match hymn_rubric_text(&hymn.title) {
            Some(rubric) => b.push_str(&format!("{{\\centering\\rubric{{{}}}\\par}}\n\n", escape_tex(rubric))),
            None => b.push_str(&format!("\\begin{{center}}{{\\small\\itshape {}}}\\end{{center}}\n\n", escape_tex(&hymn.title))),
        }
    }
    b.push_str("\\begin{hymnverses}\n");
    let mut dropped = false;
    for stanza in &hymn.stanzas {
        if let Some(rubrics) = hymn_rubric_stanza(stanza) {
            for rubric in rubrics {
                b.push_str(&format!("{{\\centering\\rubric{{{}}}\\par}}\\smallskip\n", escape_tex(rubric)));
            }
            continue;
        }
        if dropped {
            b.push_str("\\noindent ");
        }
        for (i, line) in stanza.iter().enumerate() {
            if i > 0 {
                b.push_str("\\\\\n");
            }
            if !dropped && i == 0 {
                b.push_str(&drop_cap(line));
                dropped = true;
            } else {
                b.push_str(&tex_line(line));
            }
        }
        b.push_str("\\par\\smallskip\n");
    }
    b.push_str("\\end{hymnverses}\n\n");
    b
}

/// A multi-line antiphon (a Marian antiphon): the anthem in italics, then any
/// versicle and collect as a block.
fn format_multiline_antiphon(elem: &OfficeElement) -> String {
    let mut b = String::new();
    if !elem.label.is_empty() {
        b.push_str(&format!("\n\\begin{{center}}{{\\small\\itshape {}}}\\end{{center}}\n\n", escape_tex(&elem.label)));
    }
    let (anthem, rest) = elem.text.split_once("\n\n").unwrap_or((&elem.text, ""));
    let lines: Vec<&str> = anthem.split('\n').map(str::trim).filter(|l| !l.is_empty()).collect();
    if let Some((first, more)) = lines.split_first() {
        b.push_str("{\\itshape ");
        b.push_str(&drop_cap(first));
        if !more.is_empty() {
            b.push(' ');
            b.push_str(&more.iter().map(|l| mediant_line(l)).collect::<Vec<_>>().join(" "));
        }
        b.push_str("}\\par\n");
    }
    let rest = rest.trim();
    if rest.is_empty() {
        b.push('\n');
    } else {
        b.push_str("\\smallskip\n");
        b.push_str(&format_block(rest));
    }
    b
}

fn format_short_responsory(text: &str) -> String {
    let mut b = String::new();
    let mut first_response = true;
    let mut prose: Vec<String> = Vec::new();
    let flush = |b: &mut String, prose: &mut Vec<String>| {
        if !prose.is_empty() {
            b.push_str(&format!("\\noindent {}\\par\n", prose.join(" ")));
            prose.clear();
        }
    };
    for line in parse_block(text) {
        match line.kind {
            BlockKind::Gap => {
                flush(&mut b, &mut prose);
                b.push_str("\\smallskip\n");
            }
            BlockKind::Response => {
                flush(&mut b, &mut prose);
                if first_response {
                    let (initial, word_rest, tail) = split_drop_cap(&soften_opening(&line.text));
                    b.push_str(&format!(
                        "\\shortresponse{{{}}}{{{}}}{}\\par\n",
                        tex_line(&initial),
                        tex_line(&word_rest),
                        mediant_line(&tail)
                    ));
                    first_response = false;
                } else {
                    b.push_str(&format!("\\noindent\\Rsig{{}}{}\\par\n", mediant_line(&line.text)));
                }
            }
            BlockKind::Versicle => {
                flush(&mut b, &mut prose);
                b.push_str(&format!("\\noindent\\Vsig{{}}{}\\par\n", mediant_line(&line.text)));
            }
            BlockKind::All => {
                flush(&mut b, &mut prose);
                b.push_str(&format!("\\noindent\\allsig{{}}{}\\par\n", mediant_line(&line.text)));
            }
            BlockKind::Blessing => {
                flush(&mut b, &mut prose);
                b.push_str(&format!("\\noindent\\blessingsig{{}}{}\\par\n", mediant_line(&line.text)));
            }
            BlockKind::ScriptureRef => {
                flush(&mut b, &mut prose);
                b.push_str(&format!("{{\\centering\\scriptureref{{{}}}\\par}}\n", escape_tex(&line.text)));
            }
            BlockKind::Prose => prose.push(mediant_line(&line.text)),
        }
    }
    flush(&mut b, &mut prose);
    b.push('\n');
    b
}

fn drop_cap(text: &str) -> String {
    let (initial, word_rest, tail) = split_drop_cap(&soften_opening(text));
    if initial.is_empty() {
        return tex_line(text);
    }
    format!("\\dropcap{{{}}}{{{}}}{}", tex_line(&initial), tex_line(&word_rest), mediant_line(&tail))
}

/// Go's `unicode.ToLower` of one rune.
fn lower_rune(c: char) -> char {
    let mut l = c.to_lowercase();
    match (l.next(), l.next()) {
        (Some(x), None) => x,
        _ => c,
    }
}

/// Title-cases a leading run of ALL-CAPS words ("GOD be merciful" → "God be
/// merciful") so the gilt initial takes only the first letter.
fn soften_opening(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut changed = false;
    let mut rest = s;
    loop {
        let ws = rest.len() - rest.trim_start().len();
        out.push_str(&rest[..ws]);
        rest = &rest[ws..];
        if rest.is_empty() {
            break;
        }
        let end = rest.find(char::is_whitespace).unwrap_or(rest.len());
        let word = &rest[..end];
        // PORT(inherited): Go's unicode.IsLetter/IsUpper are general-category
        // tests; Rust's are the Alphabetic/Uppercase properties. They agree on
        // the corpus.
        let letter_end = word.char_indices().rev().find(|(_, c)| c.is_alphabetic()).map_or(0, |(i, c)| i + c.len_utf8());
        if letter_end == 0 {
            out.push_str(rest);
            return out;
        }
        let (letters, trail) = word.split_at(letter_end);
        if !letters.chars().all(|c| c.is_alphabetic() && c.is_uppercase()) {
            out.push_str(rest);
            return out;
        }
        let mut chars = letters.chars();
        if letters.chars().count() >= 2 {
            out.push(chars.next().expect("non-empty"));
            out.extend(chars.map(lower_rune));
            out.push_str(trail);
            changed = true;
        } else {
            out.push_str(word);
        }
        rest = &rest[end..];
    }
    if changed { out } else { s.to_string() }
}

/// The initial, the rest of the opening word, and the remainder.
fn split_drop_cap(text: &str) -> (String, String, String) {
    let mut chars = text.chars();
    let Some(initial) = chars.next() else { return (String::new(), String::new(), String::new()) };
    let rest = chars.as_str();
    match rest.find(char::is_whitespace) {
        Some(i) if !rest.is_empty() => (initial.to_string(), rest[..i].to_string(), rest[i..].to_string()),
        _ => (initial.to_string(), rest.to_string(), String::new()),
    }
}

fn format_corporate_lord_prayer(elem: &OfficeElement) -> String {
    let (mut officiant, mut response) = (String::new(), String::new());
    for span in &elem.voice {
        match span.role {
            Some(VoiceRole::Officiant) => officiant.push_str(&span.text),
            Some(VoiceRole::Response) => response.push_str(&span.text),
            Some(VoiceRole::Priest | VoiceRole::All) | None => {}
        }
    }
    if officiant.is_empty() || response.is_empty() {
        return format_block(&elem.text);
    }
    let flow = |s: &str| s.split_whitespace().collect::<Vec<_>>().join(" ");
    format!("{}\\par\n\\noindent\\Rsig{{}}{}\\par\n\n", drop_cap(&flow(&officiant)), mediant_line(&flow(&response)))
}

fn format_collect(text: &str) -> String {
    format_block_with_opening(text, true)
}

fn format_block(text: &str) -> String {
    format_block_with_opening(text, false)
}

/// Versicles, responses, prayers, chapters, blessings, preces: hard-wrapped
/// prose lines flow into paragraphs; blank lines break them.
fn format_block_with_opening(text: &str, opening_drop_cap: bool) -> String {
    let mut b = String::new();
    let mut prose: Vec<String> = Vec::new();
    let mut dropped = false;
    let flush = |b: &mut String, prose: &mut Vec<String>, dropped: &mut bool| {
        if prose.is_empty() {
            return;
        }
        if opening_drop_cap && !*dropped {
            b.push_str(&drop_cap(&prose[0]));
            if prose.len() > 1 {
                b.push(' ');
                b.push_str(&prose[1..].iter().map(|l| mediant_line(l)).collect::<Vec<_>>().join(" "));
            }
            *dropped = true;
        } else {
            b.push_str("\\noindent ");
            b.push_str(&prose.iter().map(|l| mediant_line(l)).collect::<Vec<_>>().join(" "));
        }
        b.push_str("\\par\n");
        prose.clear();
    };
    for line in parse_block(text) {
        let sigil = match line.kind {
            BlockKind::Gap => {
                flush(&mut b, &mut prose, &mut dropped);
                b.push_str("\\smallskip\n");
                continue;
            }
            BlockKind::ScriptureRef => {
                flush(&mut b, &mut prose, &mut dropped);
                b.push_str(&format!("{{\\centering\\scriptureref{{{}}}\\par}}\n", escape_tex(&line.text)));
                continue;
            }
            BlockKind::Versicle => "\\Vsig{}",
            BlockKind::Response => "\\Rsig{}",
            BlockKind::Blessing => "\\blessingsig{}",
            BlockKind::All => "\\allsig{}",
            BlockKind::Prose => {
                prose.push(line.text);
                continue;
            }
        };
        flush(&mut b, &mut prose, &mut dropped);
        b.push_str(&format!("\\noindent{sigil}{}\\par\n", mediant_line(&line.text)));
    }
    flush(&mut b, &mut prose, &mut dropped);
    b.push('\n');
    b
}

fn format_gloria_patri(text: &str) -> String {
    let lines: Vec<&str> = text.split('\n').collect();
    let (line1, line2) = if lines.len() >= 2 { (lines[0].trim(), lines[1].trim()) } else { (text.trim(), "") };
    if line2.is_empty() {
        format!("\\noindent {}\\par\n\n", mediant_line(line1))
    } else {
        format!("\\gloriapatri{{{}}}{{{}}}\n\n", mediant_line(line1), mediant_line(line2))
    }
}

/// Escapes a line, setting a " * " pointing mediant as `\mediant{}`.
fn mediant_line(s: &str) -> String {
    match s.split_once(" * ") {
        Some((before, after)) => format!("{}\\mediant{{}}{}", tex_line(before), tex_line(after)),
        None => match s.strip_suffix(" *") {
            Some(before) => format!("{}\\mediant{{}}", tex_line(before)),
            None => tex_line(s),
        },
    }
}

/// Escapes the LaTeX special characters.
pub fn escape_tex(s: &str) -> String {
    let mut b = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '\\' => b.push_str("\\textbackslash{}"),
            '&' => b.push_str("\\&"),
            '%' => b.push_str("\\%"),
            '$' => b.push_str("\\$"),
            '#' => b.push_str("\\#"),
            '_' => b.push_str("\\_"),
            '{' => b.push_str("\\{"),
            '}' => b.push_str("\\}"),
            '~' => b.push_str("\\textasciitilde{}"),
            '^' => b.push_str("\\textasciicircum{}"),
            c => b.push(c),
        }
    }
    b
}

fn tex_line(s: &str) -> String {
    escape_tex(s).replace('✠', "\\crux{}")
}

/// The GABC slug of an element label: "Psalm 67" → "067", else a slug.
pub fn label_to_slug(label: &str, kind: ElementType) -> String {
    if label.is_empty() {
        return String::new();
    }
    if kind == ElementType::Psalm
        && let Some(after) = label.strip_prefix("Psalm ")
    {
        let num = after.split_whitespace().next().unwrap_or("");
        return format!("{num:0>3}");
    }
    slugify(label)
}

fn slugify(s: &str) -> String {
    let mut b = String::new();
    let mut prev_sep = false;
    for c in s.to_lowercase().chars() {
        if c.is_alphabetic() || c.is_numeric() {
            b.push(c);
            prev_sep = false;
        } else if !prev_sep && !b.is_empty() {
            b.push('-');
            prev_sep = true;
        }
    }
    b.trim_end_matches('-').to_string()
}

/// Spoken/silent transitions inside a plain prayer; `None` for role-bearing
/// or invalid partitions.
fn format_prayer_voice(elem: &OfficeElement) -> Option<String> {
    let mut joined = String::new();
    let mut silent = false;
    for span in &elem.voice {
        if span.role.is_some() {
            return None;
        }
        joined.push_str(&span.text);
        silent = silent || !span.spoken;
    }
    if !silent || joined != elem.text {
        return None;
    }
    let mut b = String::from("\\noindent ");
    for span in &elem.voice {
        if !span.spoken {
            b.push_str("{\\color{mutedgray} ");
        }
        for (i, paragraph) in span.text.split("\n\n").enumerate() {
            if i > 0 {
                b.push_str("\\par\n\\noindent ");
            }
            b.push_str(&mediant_line(&paragraph.replace('\n', " ")));
        }
        if !span.spoken {
            b.push('}');
        }
    }
    b.push_str("\\par\n\n");
    Some(b)
}

#[cfg(test)]
mod tests {
    use super::*;

    const PSALM_67: &str = "Psalm 67\n\nGOD be merciful unto us, and bless us * and shew us the light of his countenance:\n2. That thy way may be known upon earth * thy saving health among all nations.\nGlory be to the Father, and to the Son, and to the Holy Ghost;\nas it was in the beginning, is now, and ever shall be, world without end. Amen.\n";

    #[test]
    fn escaping() {
        for (input, want) in [
            ("hello", "hello"),
            ("a & b", "a \\& b"),
            ("100%", "100\\%"),
            ("$10", "\\$10"),
            ("#1", "\\#1"),
            ("a_b", "a\\_b"),
            ("{x}", "\\{x\\}"),
            ("~tilde", "\\textasciitilde{}tilde"),
            ("a^b", "a\\textasciicircum{}b"),
            ("back\\slash", "back\\textbackslash{}slash"),
            ("a & b % c", "a \\& b \\% c"),
        ] {
            assert_eq!(escape_tex(input), want, "{input}");
        }
        assert_eq!(tex_line("May the Lord ✠ bless us."), "May the Lord \\crux{} bless us.");
        assert_eq!(tex_line("God & ✠"), "God \\& \\crux{}");
        assert_eq!(mediant_line("God be * merciful"), "God be\\mediant{}merciful");
        assert_eq!(mediant_line("Hail *"), "Hail\\mediant{}");
    }

    #[test]
    fn slugs() {
        for (input, want) in
            [("Benedictus", "benedictus"), ("Nunc Dimittis", "nunc-dimittis"), ("hello-world", "hello-world"), ("  spaces  ", "spaces")]
        {
            assert_eq!(slugify(input), want);
        }
        for (label, kind, want) in [
            ("Psalm 67", ElementType::Psalm, "067"),
            ("Psalm 4", ElementType::Psalm, "004"),
            ("Psalm 118 (Aleph)", ElementType::Psalm, "118"),
            ("Magnificat", ElementType::Canticle, "magnificat"),
            ("Aeterne Rerum Conditor", ElementType::Hymn, "aeterne-rerum-conditor"),
            ("", ElementType::Hymn, ""),
        ] {
            assert_eq!(label_to_slug(label, kind), want);
        }
    }

    #[test]
    fn softened_openings() {
        for (input, want) in [
            ("", ""),
            ("GOD be merciful unto us,", "God be merciful unto us,"),
            ("MY SOUL cleaveth to the dust,", "My Soul cleaveth to the dust,"),
            ("O GIVE thanks unto the Lord,", "O Give thanks unto the Lord,"),
            ("O God, thou art my God,", "O God, thou art my God,"),
            ("I said, I will take heed", "I said, I will take heed"),
        ] {
            assert_eq!(soften_opening(input), want);
        }
    }

    #[test]
    fn drop_cap_boxes_only_the_first_word() {
        for (text, parts, tex) in [
            ("", ("", "", ""), ""),
            ("O", ("O", "", ""), "\\dropcap{O}{}"),
            ("Almighty God", ("A", "lmighty", " God"), "\\dropcap{A}{lmighty} God"),
            ("O God", ("O", "", " God"), "\\dropcap{O}{} God"),
            ("O\u{a0}God", ("O", "", "\u{a0}God"), "\\dropcap{O}{}\u{a0}God"),
            ("God * save us", ("G", "od", " * save us"), "\\dropcap{G}{od}\\mediant{}save us"),
        ] {
            let (a, b, c) = split_drop_cap(text);
            assert_eq!((a.as_str(), b.as_str(), c.as_str()), parts, "{text:?}");
            assert_eq!(drop_cap(text), tex);
        }
    }

    #[test]
    fn psalm_opening_takes_one_softened_initial() {
        let got = format_psalm(PSALM_67, "Psalm 67", ElementType::Psalm, None);
        assert!(got.contains("\\psalmverse{}{\\dropcap{G}{od} be merciful unto us, and bless us\\mediant{}and shew us"), "{got}");
        assert_eq!(got.matches("\\dropcap{").count(), 1);
        assert!(got.contains("\\psalmverse{2}") && got.contains("\\gloriapatri{"));

        let numbered = format_psalm("2. That thy way may be known * among all nations.\n", "Psalm 67", ElementType::Psalm, None);
        assert!(!numbered.contains("\\dropcap{"), "{numbered}");

        let sectioned = format_psalm(
            "Canticle\n\nFirst opening * alpha.\n\n[section: Part II]\n\nSECOND opening * beta.\n",
            "Canticle",
            ElementType::Canticle,
            None,
        );
        assert_eq!(sectioned.matches("\\dropcap{").count(), 2, "{sectioned}");
        assert!(sectioned.contains("\\canticlesection{Part II}") && sectioned.contains("\\dropcap{S}{econd} opening"));
    }

    #[test]
    fn chant_scores_replace_text_only_when_found() {
        let base = |category: &str, slug: &str| (category == "psalms" && slug == "067").then(|| "data/texts/chant/psalms/067".to_string());
        let chant = Chant { base: &base };
        let got = format_psalm(PSALM_67, "Psalm 67", ElementType::Psalm, Some(&chant));
        assert_eq!(got, "\\gregorioscore{data/texts/chant/psalms/067}\n\n");
        let missing = format_psalm(PSALM_67, "Psalm 68", ElementType::Psalm, Some(&chant));
        assert!(missing.contains("\\psalmverse"));

        let hymn = "Aeterne rerum conditor\n\nO Framer of the earth and sky,\nRuler of all things high and low.\n";
        let text = format_hymn(hymn, "Aeterne Rerum Conditor", Some(&chant));
        assert!(text.contains("\\dropcap{O}{} Framer"), "{text}");
    }

    #[test]
    fn multiline_antiphon_flows_the_anthem() {
        let mut elem = OfficeElement::new(
            ElementType::Antiphon,
            "Hail, holy Queen, Mother of mercy,\nour life, our sweetness, and our hope.\n\nV. Pray for us, O holy Mother of God.\nR. That we may be made worthy of the promises of Christ.",
        );
        elem.label = "Salve Regina".into();
        let got = format_multiline_antiphon(&elem);
        assert!(got.contains("\\small\\itshape Salve Regina"));
        assert!(
            got.contains("{\\itshape \\dropcap{H}{ail,} holy Queen, Mother of mercy, our life, our sweetness, and our hope.}"),
            "{got}"
        );
        assert!(got.contains("\\Vsig{}") && got.contains("\\Rsig{}"));

        let only =
            format_multiline_antiphon(&OfficeElement::new(ElementType::Antiphon, "Line one of the anthem,\nline two of the anthem."));
        assert!(only.contains("{\\itshape \\dropcap{L}{ine} one of the anthem, line two of the anthem.}"), "{only}");
    }

    #[test]
    fn gloria_patri() {
        let got = format_gloria_patri("Glory be to the Father;\nas it was in the beginning.");
        assert_eq!(got, "\\gloriapatri{Glory be to the Father;}{as it was in the beginning.}\n\n");
        assert_eq!(format_gloria_patri("Glory be"), "\\noindent Glory be\\par\n\n");
    }
}
