package output

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"unicode"
	"unicode/utf8"

	"github.com/orthodoxwest/office/internal/models"
	"github.com/orthodoxwest/office/internal/texts"
)

// FormatOfficeHourTeX formats a composed office hour as a LaTeX document.
// The resulting string is a complete .tex file suitable for compilation
// with lualatex (required for gregoriotex and fontspec).
//
// When chant is true and a .gabc file exists at
// data/texts/chant/{category}/{slug}.gabc, the element is rendered as
// \gregorioscore{path}; otherwise formatted text is emitted.
func FormatOfficeHourTeX(hour *models.OfficeHour, dataDir string, chant bool) string {
	if chant && filepath.IsAbs(dataDir) {
		// \gregorioscore paths must be relative to CWD; kpathsea blocks writes
		// to absolute paths outside the TeX run directory.
		if cwd, err := os.Getwd(); err == nil {
			if rel, err := filepath.Rel(cwd, dataDir); err == nil {
				dataDir = rel
			}
		}
	}

	var b strings.Builder

	b.WriteString(texPreamble(hour))
	b.WriteString(texTitleBlock(hour))

	for _, section := range hour.Sections {
		b.WriteString(texSection(section, dataDir, chant))
	}

	b.WriteString("\n\\end{document}\n")
	return b.String()
}

// texPreamble returns the LaTeX document preamble.
func texPreamble(hour *models.OfficeHour) string {
	var b strings.Builder
	fmt.Fprintf(&b, "%% Auto-generated by office tex — %s %s\n",
		hour.Hour, hour.Date.Format("2006-01-02"))
	b.WriteString(`%% Compile with: lualatex <file>.tex
%% For booklet imposition: pdfjam --booklet true --paper letter <file>.pdf

\documentclass[10pt]{article}

\usepackage[
  paperwidth=5.5in,
  paperheight=8.5in,
  top=0.65in,
  bottom=0.75in,
  inner=0.7in,
  outer=0.5in
]{geometry}

\usepackage{fontspec}
\usepackage{gregoriotex}
\gresetcompilegabc{auto}
\usepackage{xcolor}
\usepackage{lettrine}
\usepackage{microtype}
\microtypesetup{verbose=silent}
\usepackage{setspace}

% Fonts — requires EB Garamond to be installed on the system.
% Small caps carry web-like tracking everywhere (\scshape, \textsc), matching
% the letterspaced section headings, psalm labels, and Ant. sigils online.
\setmainfont{EB Garamond}[Ligatures=TeX,SmallCapsFeatures={LetterSpace=8.0}]

% Prayer leading sits a touch deeper than LaTeX's default, as the web hour
% sets body text at 1.6 and psalm/hymn verse at 1.75.
\linespread{1.25}

% Colors — the web Nave palette, so print and screen share one set of inks:
% rubric red, gilding gold with its hairline, and muted grey for verse
% numbers, labels, and pointing marks.
\definecolor{rubricred}{rgb}{0.545,0.102,0.102}
\definecolor{ornamentgold}{rgb}{0.604,0.451,0.157}
\definecolor{goldline}{rgb}{0.788,0.675,0.447}
\definecolor{mutedgray}{rgb}{0.420,0.365,0.333}

% ✠ (U+2720) fallback via Noto Sans Symbols (Dingbats block)
\newfontface\CrossFont[Path=/usr/share/fonts/truetype/noto/,Scale=MatchLowercase]{NotoSansSymbols-Black.ttf}
\newcommand{\crux}{{\color{rubricred}{\Large\CrossFont\symbol{"2720}}}}

% Rubrics are smaller red roman; quoted prayer remains ordinary black roman.
\newcommand{\rubric}[1]{{\color{rubricred}\small\normalfont #1}}
% A prayer quoted inside a rubric remains ordinary black text.
\newcommand{\rubricprayed}[1]{{\color{black}\normalfont #1}}
% Scripture references share the rubric treatment without becoming instructions.
\newcommand{\scriptureref}[1]{{\color{rubricred}\small\normalfont #1}}

% Gilded two-line initials. All call sites are semantic spoken openings, never
% private/secret prayer text. Only the initial itself is gilt: the rest of the
% opening word stays ordinary prose, as ::first-letter does on the web hour.
\renewcommand{\LettrineTextFont}{\normalfont}
\newcommand{\dropcap}[2]{\lettrine[lines=2,lhang=0.1,nindent=0.1em]{\color{ornamentgold}#1}{#2}}

% Section heading: centered small caps with open air, as the web hour centers
% each transition in tracked small caps.
\newcommand{\sectionheading}[1]{%
  \bigskip\begin{center}{\scshape #1}\end{center}\smallskip\noindent%
}

% Mid-canticle section break (e.g. the two-part structure of Deut 32):
% centered muted italic, as the web canticle-section line.
\newcommand{\canticlesection}[1]{%
  \smallskip\begin{center}{\small\color{mutedgray}\itshape #1}\end{center}\smallskip\noindent%
}

% Psalm/canticle label: the number in body-size small caps, the Latin incipit in italic
% beside it, as a printed diurnal sets them. #2 is empty when no incipit is
% recorded, in which case the label stands alone.
\newcommand{\psalmlabel}[2]{%
  \begin{center}{\color{mutedgray}\scshape #1}%
  \if\relax\detokenize{#2}\relax\else{\color{mutedgray}\itshape\enspace$\cdot$\enspace #2}\fi%
  \end{center}\smallskip%
}

% Pointing mediant: muted and raised to the optical middle of the line, as the
% web verse renderer lifts the asterisk clear of the ascenders.
\newcommand{\mediant}{\,\raisebox{0.25em}{\small\color{mutedgray}*}\,}

% Psalm verses environment and command. Verses breathe a little deeper than
% prose, as psalm-verses does online.
\newenvironment{psalmverses}{%
  \setlength{\parindent}{0pt}%
  \setlength{\parskip}{2pt}%
  \setstretch{1.35}%
}{%
  \par%
}

% Hymn stanza environment: deeper verse leading, as hymn-verses does.
\newenvironment{hymnverses}{%
  \setstretch{1.35}%
}{%
  \par%
}

% \psalmverse{num}{text} — num is empty for unnumbered first verse.
% Numbered verses hang from a muted right-aligned gutter so every spoken line
% shares one left edge, as verse-num does on the web hour.
\newcommand{\psalmverse}[2]{%
  \if\relax\detokenize{#1}\relax%
    \noindent #2\par%
  \else%
    \noindent\hangindent=2em\hangafter=1\makebox[1.4em][r]{{\small\color{mutedgray}#1}}\hspace{0.6em}#2\par%
  \fi%
}

% Gloria Patri: two verses, each pointed at its own mediant, on their own
% lines, standing a little apart from the verses above as its own stanza.
\newcommand{\gloriapatri}[2]{\medskip\noindent #1\\#2\par}

% Spoken-role sigils set in rubric red, as the web sigil column does.
% \Vbar/\Rbar come from gregoriotex, which the preamble loads above.
\newcommand{\Vsig}{{\color{rubricred}\Vbar{}}}
\newcommand{\Rsig}{{\color{rubricred}\Rbar{}}}
\newcommand{\allsig}{{\color{rubricred}\scshape All:}\kern0.3em{}}
\newcommand{\blessingsig}{{\color{rubricred}Blessing.}\kern0.3em{}}

% Antiphon: a red small-cap sigil with the body in ordinary roman, hanging so
% a wrapped remainder tucks under its own line, as body antiphons do online.
\newcommand{\ant}[1]{\noindent\hangindent=1.35em\hangafter=1{\color{rubricred}\scshape Ant.}\hspace{0.3em}#1\par}
% Opening acclamation (not an antiphon)
\newcommand{\acclamation}[1]{\noindent #1\par}
% Initial response of a Short Responsory. No \par here — call sites append the
% rest of the response (and a single trailing \par) so lettrine can wrap line 2.
\newcommand{\shortresponse}[2]{\dropcap{#1}{#2}}

\setlength{\parskip}{4pt}
\setlength{\parindent}{0pt}
\pagestyle{plain}

\begin{document}
`)
	return b.String()
}

// texTitleBlock returns the title block for the hour: the hour name framed by
// double gold hairlines with a lozenge, as the web hour-header frames its
// title, with the day and season kept quiet beneath it.
func texTitleBlock(hour *models.OfficeHour) string {
	var b strings.Builder
	b.WriteString("\\begin{center}\n")
	b.WriteString("  {\\color{goldline}\\rule{\\linewidth}{0.6pt}}\\\\[1pt]\n")
	b.WriteString("  {\\color{goldline}\\rule{\\linewidth}{0.6pt}}\\\\[6pt]\n")
	fmt.Fprintf(&b, "  {\\Large\\scshape The Order for %s}\\\\[4pt]\n", escapeTeX(hour.Hour))
	fmt.Fprintf(&b, "  {\\normalsize %s}\\\\[2pt]\n", escapeTeX(hour.Date.Format("Monday, January 2, 2006")))
	if hour.Feast != "" {
		fmt.Fprintf(&b, "  {\\normalsize\\itshape %s}\\\\[2pt]\n", escapeTeX(hour.Feast))
	}
	fmt.Fprintf(&b, "  {\\small\\color{mutedgray}Season: %s \\quad$\\cdot$\\quad Color: %s}\\\\[6pt]\n",
		escapeTeX(string(hour.Season)), escapeTeX(string(hour.Color)))
	b.WriteString("  {\\color{goldline}\\rule{\\linewidth}{0.6pt}}\\\\[1pt]\n")
	b.WriteString("  {\\color{goldline}\\rule{\\linewidth}{0.6pt}}\\\\[4pt]\n")
	b.WriteString("  {\\color{ornamentgold}\\small$\\diamond$}\n")
	b.WriteString("\\end{center}\n\n")
	return b.String()
}

// texSection formats a single OfficeSection.
func texSection(section models.OfficeSection, dataDir string, chant bool) string {
	var b strings.Builder

	if section.Label != "" {
		fmt.Fprintf(&b, "\\sectionheading{%s}\n\n", escapeTeX(section.Label))
	}

	for _, elem := range section.Elements {
		b.WriteString(texElement(elem, dataDir, chant))
	}

	return b.String()
}

// texElement dispatches to the appropriate formatter for each element type.
func texElement(elem models.OfficeElement, dataDir string, chant bool) string {
	var b strings.Builder

	switch elem.Type {
	case models.Rubric:
		b.WriteString(formatRubricTeX(elem))

	case models.Heading:
		fmt.Fprintf(&b, "\\sectionheading{%s}\n\n", escapeTeX(elem.Text))

	case models.Antiphon:
		if text := elem.DisplayText(); text != "" {
			if strings.Contains(text, "\n") {
				// Multiline (e.g. Marian) always uses the full Text path via
				// formatMultilineAntiphonTeX; announced forms are single-line.
				b.WriteString(formatMultilineAntiphonTeX(elem))
			} else {
				fmt.Fprintf(&b, "\\ant{%s}\n\n", texMediantLine(text))
			}
		}
	case models.OpeningAcclamation:
		fmt.Fprintf(&b, "\\acclamation{%s}\n\n", texMediantLine(elem.Text))

	case models.Psalm, models.Canticle:
		if elem.Label != "" {
			fmt.Fprintf(&b, "\n\\psalmlabel{%s}{%s}\n\n",
				escapeTeX(elem.Label), escapeTeX(elem.Incipit))
		}
		b.WriteString(formatPsalmTeX(elem.Text, dataDir, elem.Label, elem.Type, chant))

	case models.Hymn:
		if elem.Label != "" {
			fmt.Fprintf(&b, "\n\\begin{center}{\\small\\itshape %s}\\end{center}\n\n", escapeTeX(elem.Label))
		}
		b.WriteString(formatHymnTeX(elem.Text, dataDir, elem.Label, chant))

	case models.PsalmDoxology:
		b.WriteString(formatGloriaPatriTeX(elem.Text))

	case models.Prayer, models.Reading:
		if len(elem.Voice) == 1 && !elem.Voice[0].Spoken && elem.Voice[0].Text == elem.Text {
			b.WriteString("{\\color{mutedgray}\n")
			b.WriteString(formatLiturgicalBlockTeX(elem.Text))
			b.WriteString("}\n")
		} else if turns := elem.SpeakerTurns(); len(turns) > 0 {
			for _, turn := range turns {
				fmt.Fprintf(&b, "\\noindent\\rubric{\\scshape %s}\\par\\nopagebreak\n", turn.Role.Label())
				b.WriteString(formatLiturgicalBlockTeX(turn.Text))
			}
		} else {
			b.WriteString(formatLiturgicalBlockTeX(elem.Text))
		}
	case models.Doxology, models.Versicle, models.Response, models.Dialogue,
		models.Blessing, models.Preces:
		b.WriteString(formatLiturgicalBlockTeX(elem.Text))
	// A chapter's opening paragraph takes the spoken initial like a collect's,
	// matching the web chapter's dropped first letter.
	case models.Collect:
		if len(elem.Voice) == 2 && elem.Voice[0].Spoken && !elem.Voice[1].Spoken &&
			elem.Voice[0].Text+elem.Voice[1].Text == elem.Text {
			b.WriteString(formatCollectTeX(elem.Voice[0].Text))
			b.WriteString("{\\color{mutedgray}\n")
			b.WriteString(formatLiturgicalBlockTeX(elem.Voice[1].Text))
			b.WriteString("}\n")
		} else {
			b.WriteString(formatCollectTeX(elem.Text))
		}
	case models.Chapter:
		b.WriteString(formatCollectTeX(elem.Text))
	case models.ShortResponsory:
		b.WriteString(formatShortResponsoryTeX(elem.Text))
	case models.CorporateLordPrayer:
		b.WriteString(formatCorporateLordPrayerTeX(elem))
	}

	return b.String()
}

func formatRubricTeX(elem models.OfficeElement) string {
	if len(elem.RubricSpans) == 0 {
		return fmt.Sprintf("\\rubric{%s}\n\n", escapeTeX(elem.Text))
	}
	var b strings.Builder
	b.WriteString("\\rubric{")
	for _, span := range elem.RubricSpans {
		if span.Prayed {
			fmt.Fprintf(&b, "\\rubricprayed{%s}", texLine(span.Text))
		} else {
			b.WriteString(escapeTeX(span.Text))
		}
	}
	b.WriteString("}\n\n")
	return b.String()
}

// formatPsalmTeX renders a psalm or canticle element.
// When chant is true, checks for a .gabc file first; falls back to text rendering.
func formatPsalmTeX(text, dataDir, label string, elemType models.ElementType, chant bool) string {
	category := "psalms"
	if elemType == models.Canticle {
		category = "canticles"
	}
	slug := labelToSlug(label, elemType)
	if chant && hasGABC(dataDir, category, slug) {
		return fmt.Sprintf("\\gregorioscore{%s}\n\n", gabcBase(dataDir, category, slug))
	}

	psalm := texts.ParsePsalm(text)

	var b strings.Builder

	if psalm.ScriptureRef != "" {
		fmt.Fprintf(&b, "{\\centering\\scriptureref{%s}\\par}\n\n", escapeTeX(psalm.ScriptureRef))
	}

	b.WriteString("\\begin{psalmverses}\n")

	// The opening verse of each psalm-verses block takes the gilt initial, as
	// the web hour drops the first letter of every first verse. A Gloria is
	// never the dropped verse; a section break re-arms the opening.
	firstVerse := true

	for _, item := range psalm.Items {
		switch item.Kind {
		case texts.PsalmSection:
			b.WriteString("\\end{psalmverses}\n")
			fmt.Fprintf(&b, "\\canticlesection{%s}\n", escapeTeX(item.Heading))
			b.WriteString("\\begin{psalmverses}\n")
			firstVerse = true

		case texts.PsalmGloria:
			firstVerse = false
			if item.Second == "" {
				// Malformed Gloria (missing second line) — emit what we have.
				fmt.Fprintf(&b, "\\psalmverse{}{%s}\n", texMediantLine(item.First))
				continue
			}
			fmt.Fprintf(&b, "\\gloriapatri{%s}{%s}\n", texMediantLine(item.First), texMediantLine(item.Second))

		default:
			if firstVerse {
				firstVerse = false
				if item.Number == "" {
					if item.Second == "" {
						fmt.Fprintf(&b, "\\psalmverse{}{%s}\n", texDropCap(item.First))
						continue
					}
					fmt.Fprintf(&b, "\\psalmverse{}{%s\\mediant{}%s}\n",
						texDropCap(item.First), texLine(item.Second))
					continue
				}
				// A numbered opening keeps plain text: with no unnumbered
				// paragraph the gilt initial has no home, as online.
			}
			if item.Second == "" {
				fmt.Fprintf(&b, "\\psalmverse{%s}{%s}\n", item.Number, texLine(item.First))
				continue
			}
			fmt.Fprintf(&b, "\\psalmverse{%s}{%s\\mediant{}%s}\n",
				item.Number, texLine(item.First), texLine(item.Second))
		}
	}

	b.WriteString("\\end{psalmverses}\n\n")
	return b.String()
}

// formatHymnTeX renders a hymn element as stanza paragraphs.
//
// The composed element usually arrives with its Latin incipit already in the
// label (the engine peels it), so this must parse with the shared rule rather
// than dropping everything above the first blank line — that dropped the
// opening stanza of every hymn.
func formatHymnTeX(text, dataDir, label string, chant bool) string {
	slug := labelToSlug(label, models.Hymn)
	if chant && hasGABC(dataDir, "hymns", slug) {
		return fmt.Sprintf("\\gregorioscore{%s}\n\n", gabcBase(dataDir, "hymns", slug))
	}

	hymn := texts.ParseHymn(text)

	var b strings.Builder
	if hymn.Title != "" {
		if rubric, ok := texts.HymnRubricText(hymn.Title); ok {
			fmt.Fprintf(&b, "{\\centering\\rubric{%s}\\par}\n\n", escapeTeX(rubric))
		} else {
			fmt.Fprintf(&b, "\\begin{center}{\\small\\itshape %s}\\end{center}\n\n", escapeTeX(hymn.Title))
		}
	}
	b.WriteString("\\begin{hymnverses}\n")
	dropped := false
	for _, stanza := range hymn.Stanzas {
		if rubrics, ok := texts.HymnRubricStanza(stanza); ok {
			for _, rubric := range rubrics {
				fmt.Fprintf(&b, "{\\centering\\rubric{%s}\\par}\\smallskip\n", escapeTeX(rubric))
			}
			continue
		}
		if dropped {
			b.WriteString("\\noindent ")
		}
		for i, line := range stanza {
			if i > 0 {
				b.WriteString("\\\\\n")
			}
			if !dropped && i == 0 {
				b.WriteString(texDropCap(line))
				dropped = true
			} else {
				b.WriteString(texLine(line))
			}
		}
		b.WriteString("\\par\\smallskip\n")
	}

	b.WriteString("\\end{hymnverses}\n\n")
	return b.String()
}

// formatMultilineAntiphonTeX renders a multi-line antiphon (e.g., a Marian
// antiphon). The first paragraph is the anthem proper and is set in italics;
// any remainder (versicle, collect) uses the standard liturgical block.
func formatMultilineAntiphonTeX(elem models.OfficeElement) string {
	var b strings.Builder

	if elem.Label != "" {
		fmt.Fprintf(&b, "\n\\begin{center}{\\small\\itshape %s}\\end{center}\n\n", escapeTeX(elem.Label))
	}

	anthem, rest, _ := strings.Cut(elem.Text, "\n\n")
	var anthemLines []string
	for line := range strings.SplitSeq(anthem, "\n") {
		if line = strings.TrimSpace(line); line != "" {
			anthemLines = append(anthemLines, line)
		}
	}
	if len(anthemLines) > 0 {
		b.WriteString("{\\itshape ")
		b.WriteString(texDropCap(anthemLines[0]))
		if len(anthemLines) > 1 {
			b.WriteByte(' ')
			b.WriteString(strings.Join(texMediantLines(anthemLines[1:]), " "))
		}
		b.WriteString("}\\par\n")
	}
	if rest = strings.TrimSpace(rest); rest != "" {
		b.WriteString("\\smallskip\n")
		b.WriteString(formatLiturgicalBlockTeX(rest))
	} else {
		b.WriteString("\n")
	}
	return b.String()
}

func formatShortResponsoryTeX(text string) string {
	var b strings.Builder
	firstResponse := true
	var proseLines []string
	flushProse := func() {
		if len(proseLines) == 0 {
			return
		}
		fmt.Fprintf(&b, "\\noindent %s\\par\n", strings.Join(proseLines, " "))
		proseLines = nil
	}
	for _, line := range texts.ParseBlock(text) {
		switch line.Kind {
		case texts.BlockGap:
			flushProse()
			b.WriteString("\\smallskip\n")
		case texts.BlockResponse:
			flushProse()
			if firstResponse {
				initial, firstWordRest, tail := splitDropCap(softenTeXOpening(line.Text))
				fmt.Fprintf(&b, "\\shortresponse{%s}{%s}%s\\par\n", texLine(initial), texLine(firstWordRest), texMediantLine(tail))
				firstResponse = false
			} else {
				fmt.Fprintf(&b, "\\noindent\\Rsig{}%s\\par\n", texMediantLine(line.Text))
			}
		case texts.BlockVersicle:
			flushProse()
			fmt.Fprintf(&b, "\\noindent\\Vsig{}%s\\par\n", texMediantLine(line.Text))
		case texts.BlockAll:
			flushProse()
			fmt.Fprintf(&b, "\\noindent\\allsig{}%s\\par\n", texMediantLine(line.Text))
		case texts.BlockBlessing:
			flushProse()
			fmt.Fprintf(&b, "\\noindent\\blessingsig{}%s\\par\n", texMediantLine(line.Text))
		case texts.BlockScriptureRef:
			flushProse()
			fmt.Fprintf(&b, "{\\centering\\scriptureref{%s}\\par}\n", escapeTeX(line.Text))
		default:
			proseLines = append(proseLines, texMediantLine(line.Text))
		}
	}
	flushProse()
	b.WriteString("\n")
	return b.String()
}

func splitInitial(text string) (initial, rest string) {
	if text == "" {
		return "", ""
	}
	r, n := utf8.DecodeRuneInString(text)
	return string(r), text[n:]
}

func texDropCap(text string) string {
	initial, firstWordRest, tail := splitDropCap(softenTeXOpening(text))
	if initial == "" {
		return texLine(text)
	}
	return fmt.Sprintf("\\dropcap{%s}{%s}%s", texLine(initial), texLine(firstWordRest), texMediantLine(tail))
}

// softenTeXOpening mirrors render.softenDropCapOpening for print: it
// title-cases a run of leading ALL-CAPS words so the gilt initial takes only
// the first letter and the rest of the word reads as prose. Without this,
// Coverdale openings like "GOD be merciful" set a gilt "G" beside full-caps
// "OD". Single-letter words (O, I) are left alone; multi-letter ALL-CAPS
// words are title-cased until a mixed-case word stops the run.
func softenTeXOpening(s string) string {
	if s == "" {
		return s
	}
	var b strings.Builder
	b.Grow(len(s))
	i := 0
	changed := false
	for i < len(s) {
		for i < len(s) {
			r, size := utf8.DecodeRuneInString(s[i:])
			if !unicode.IsSpace(r) {
				break
			}
			b.WriteRune(r)
			i += size
		}
		if i >= len(s) {
			break
		}
		wordStart := i
		for i < len(s) {
			r, size := utf8.DecodeRuneInString(s[i:])
			if unicode.IsSpace(r) {
				break
			}
			i += size
		}
		word := s[wordStart:i]
		letterEnd := len(word)
		for letterEnd > 0 {
			r, size := utf8.DecodeLastRuneInString(word[:letterEnd])
			if unicode.IsLetter(r) {
				break
			}
			letterEnd -= size
		}
		if letterEnd == 0 {
			b.WriteString(s[wordStart:])
			return b.String()
		}
		letters := word[:letterEnd]
		trail := word[letterEnd:]
		runes := []rune(letters)
		allCaps := true
		for _, r := range runes {
			if !unicode.IsLetter(r) || !unicode.IsUpper(r) {
				allCaps = false
				break
			}
		}
		if !allCaps {
			b.WriteString(s[wordStart:])
			return b.String()
		}
		if len(runes) >= 2 {
			b.WriteRune(runes[0])
			for _, r := range runes[1:] {
				b.WriteRune(unicode.ToLower(r))
			}
			b.WriteString(trail)
			changed = true
		} else {
			b.WriteString(word)
		}
	}
	if !changed {
		return s
	}
	return b.String()
}

// splitDropCap gives lettrine only the remainder of the opening word; its
// second argument is boxed internally, so passing a whole paragraph prevents
// normal line wrapping. The tail remains ordinary flowing text after it.
func splitDropCap(text string) (initial, firstWordRest, tail string) {
	initial, rest := splitInitial(text)
	if initial == "" || rest == "" {
		return initial, rest, ""
	}
	i := strings.IndexFunc(rest, unicode.IsSpace)
	if i < 0 {
		return initial, rest, ""
	}
	return initial, rest[:i], rest[i:]
}

// texMediantLines maps texMediantLine over sense-lines joined into a flowing
// paragraph, so pointed prose keeps the \mediant{} mark instead of a literal
// asterisk.
func texMediantLines(lines []string) []string {
	formatted := make([]string, len(lines))
	for i, line := range lines {
		formatted[i] = texMediantLine(line)
	}
	return formatted
}

func formatCorporateLordPrayerTeX(elem models.OfficeElement) string {
	var officiant, response strings.Builder
	for _, span := range elem.Voice {
		switch span.Role {
		case models.VoiceOfficiant:
			officiant.WriteString(span.Text)
		case models.VoiceResponse:
			response.WriteString(span.Text)
		}
	}
	if officiant.Len() == 0 || response.Len() == 0 {
		return formatLiturgicalBlockTeX(elem.Text)
	}
	flow := func(s string) string { return strings.Join(strings.Fields(s), " ") }
	return fmt.Sprintf("%s\\par\n\\noindent\\Rsig{}%s\\par\n\n",
		texDropCap(flow(officiant.String())), texMediantLine(flow(response.String())))
}

// formatCollectTeX gives the first spoken prose paragraph of a collect its
// traditional initial without applying that treatment to generic prayers.
func formatCollectTeX(text string) string {
	return formatLiturgicalBlockTeXWithOpeningDropCap(text, true)
}

// formatLiturgicalBlockTeX renders versicles, responses, prayers, chapters,
// blessings, and preces with appropriate LaTeX markup. Consecutive prose
// lines are hard-wrapped sense-lines in the corpus, so they are joined into
// a flowing paragraph; blank lines mark paragraph breaks.
func formatLiturgicalBlockTeX(text string) string {
	return formatLiturgicalBlockTeXWithOpeningDropCap(text, false)
}

func formatLiturgicalBlockTeXWithOpeningDropCap(text string, openingDropCap bool) string {
	var b strings.Builder

	var proseLines []string
	droppedOpening := false
	flushProse := func() {
		if len(proseLines) == 0 {
			return
		}
		if openingDropCap && !droppedOpening {
			b.WriteString(texDropCap(proseLines[0]))
			if len(proseLines) > 1 {
				b.WriteByte(' ')
				b.WriteString(strings.Join(texMediantLines(proseLines[1:]), " "))
			}
			droppedOpening = true
		} else {
			b.WriteString("\\noindent ")
			b.WriteString(strings.Join(texMediantLines(proseLines), " "))
		}
		b.WriteString("\\par\n")
		proseLines = nil
	}

	for _, line := range texts.ParseBlock(text) {
		switch line.Kind {
		case texts.BlockGap:
			flushProse()
			b.WriteString("\\smallskip\n")
		case texts.BlockScriptureRef:
			flushProse()
			fmt.Fprintf(&b, "{\\centering\\scriptureref{%s}\\par}\n", escapeTeX(line.Text))
		case texts.BlockVersicle:
			flushProse()
			fmt.Fprintf(&b, "\\noindent\\Vsig{}%s\\par\n", texMediantLine(line.Text))
		case texts.BlockResponse:
			flushProse()
			fmt.Fprintf(&b, "\\noindent\\Rsig{}%s\\par\n", texMediantLine(line.Text))
		case texts.BlockBlessing:
			flushProse()
			fmt.Fprintf(&b, "\\noindent\\blessingsig{}%s\\par\n", texMediantLine(line.Text))
		case texts.BlockAll:
			flushProse()
			fmt.Fprintf(&b, "\\noindent\\allsig{}%s\\par\n", texMediantLine(line.Text))
		default:
			proseLines = append(proseLines, line.Text)
		}
	}

	flushProse()
	b.WriteString("\n")
	return b.String()
}

// formatGloriaPatriTeX renders a two-line psalm-doxology (Gloria Patri), each
// line pointed at its own mediant.
func formatGloriaPatriTeX(text string) string {
	lines := strings.Split(text, "\n")
	var line1, line2 string
	if len(lines) >= 2 {
		line1 = strings.TrimSpace(lines[0])
		line2 = strings.TrimSpace(lines[1])
	} else {
		line1 = strings.TrimSpace(text)
	}
	if line2 != "" {
		return fmt.Sprintf("\\gloriapatri{%s}{%s}\n\n", texMediantLine(line1), texMediantLine(line2))
	}
	return fmt.Sprintf("\\noindent %s\\par\n\n", texMediantLine(line1))
}

// texMediantLine escapes a line for TeX, rendering an embedded " * " pointing
// mediant as \mediant{} rather than a literal asterisk. A trailing " * "
// (the first half of a pointed pair whose remainder follows on the next
// source line, as in the Ave Regina opening) keeps the mark with no second
// half, mirroring chantLineHTML on the web hour.
func texMediantLine(s string) string {
	before, after, found := strings.Cut(s, " * ")
	if !found {
		if before, ok := strings.CutSuffix(s, " *"); ok {
			return texLine(before) + `\mediant{}`
		}
		return texLine(s)
	}
	return texLine(before) + `\mediant{}` + texLine(after)
}

// escapeTeX escapes LaTeX special characters in plain text.
// Single-pass rune scanner avoids the ordering problem of chained ReplaceAll calls.
func escapeTeX(s string) string {
	var b strings.Builder
	b.Grow(len(s))
	for _, r := range s {
		switch r {
		case '\\':
			b.WriteString(`\textbackslash{}`)
		case '&':
			b.WriteString(`\&`)
		case '%':
			b.WriteString(`\%`)
		case '$':
			b.WriteString(`\$`)
		case '#':
			b.WriteString(`\#`)
		case '_':
			b.WriteString(`\_`)
		case '{':
			b.WriteString(`\{`)
		case '}':
			b.WriteString(`\}`)
		case '~':
			b.WriteString(`\textasciitilde{}`)
		case '^':
			b.WriteString(`\textasciicircum{}`)
		default:
			b.WriteRune(r)
		}
	}
	return b.String()
}

// texLine escapes LaTeX specials and replaces the ✠ cross with \crux{}.
func texLine(s string) string {
	return strings.ReplaceAll(escapeTeX(s), "✠", `\crux{}`)
}

// GABC helpers

// gabcPath returns the full path to a .gabc file (for existence checks).
func gabcPath(dataDir, category, slug string) string {
	return filepath.Join(dataDir, "texts", "chant", category, slug+".gabc")
}

// gabcBase returns the path without the .gabc extension, as required by \gregorioscore.
// Gregoriotex appends .gabc (and .gtex) itself.
func gabcBase(dataDir, category, slug string) string {
	return filepath.Join(dataDir, "texts", "chant", category, slug)
}

func hasGABC(dataDir, category, slug string) bool {
	if dataDir == "" || slug == "" {
		return false
	}
	_, err := os.Stat(gabcPath(dataDir, category, slug))
	return err == nil
}

// labelToSlug converts an element label to a filesystem slug for GABC lookup.
//   - Psalm "Psalm 67" → "067"
//   - Psalm "Psalm 118" → "118"
//   - Canticle "Benedictus" → "benedictus"
//   - Hymn "Aeterne Rerum Conditor" → "aeterne-rerum-conditor"
func labelToSlug(label string, elemType models.ElementType) string {
	if label == "" {
		return ""
	}
	switch elemType {
	case models.Psalm:
		// "Psalm N" → zero-padded 3-digit string
		after, ok := strings.CutPrefix(label, "Psalm ")
		if !ok {
			return slugify(label)
		}
		// Strip sub-section like "118 (Aleph)" → "118"
		num := strings.Fields(after)[0]
		if len(num) < 3 {
			num = strings.Repeat("0", 3-len(num)) + num
		}
		return num
	default:
		return slugify(label)
	}
}

// slugify converts a string to a lowercase hyphen-separated slug.
func slugify(s string) string {
	s = strings.ToLower(s)
	var b strings.Builder
	prevWasSep := false
	for _, r := range s {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			b.WriteRune(r)
			prevWasSep = false
		} else if !prevWasSep && b.Len() > 0 {
			b.WriteRune('-')
			prevWasSep = true
		}
	}
	return strings.TrimRight(b.String(), "-")
}
