package output

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"unicode"

	"github.com/orthodoxwest/office/internal/models"
)

// FormatOfficeHourTeX formats a composed office hour as a LaTeX document.
// The resulting string is a complete .tex file suitable for compilation
// with lualatex (required for gregoriotex and fontspec).
//
// When chant is true and a .gabc file exists at
// data/texts/chant/{category}/{slug}.gabc, the element is rendered as
// \gregorioscore{path}; otherwise formatted text is emitted.
func FormatOfficeHourTeX(hour *models.OfficeHour, dataDir string, chant bool) string {
	if chant && filepath.IsAbs(dataDir) {
		// \gregorioscore paths must be relative to CWD; kpathsea blocks writes
		// to absolute paths outside the TeX run directory.
		if cwd, err := os.Getwd(); err == nil {
			if rel, err := filepath.Rel(cwd, dataDir); err == nil {
				dataDir = rel
			}
		}
	}

	var b strings.Builder

	b.WriteString(texPreamble(hour))
	b.WriteString(texTitleBlock(hour))

	for _, section := range hour.Sections {
		b.WriteString(texSection(section, dataDir, chant))
	}

	b.WriteString("\n\\end{document}\n")
	return b.String()
}

// texPreamble returns the LaTeX document preamble.
func texPreamble(hour *models.OfficeHour) string {
	var b strings.Builder
	fmt.Fprintf(&b, "%% Auto-generated by office tex — %s %s\n",
		hour.Hour, hour.Date.Format("2006-01-02"))
	b.WriteString(`%% Compile with: lualatex <file>.tex
%% For booklet imposition: pdfjam --booklet true --paper letter <file>.pdf

\documentclass[10pt]{article}

\usepackage[
  paperwidth=5.5in,
  paperheight=8.5in,
  top=0.65in,
  bottom=0.75in,
  inner=0.7in,
  outer=0.5in
]{geometry}

\usepackage{fontspec}
\usepackage{gregoriotex}
\gresetcompilegabc{auto}
\usepackage{xcolor}
\usepackage{microtype}
\microtypesetup{verbose=silent}


% Fonts — requires EB Garamond to be installed on the system
\setmainfont{EB Garamond}[Ligatures=TeX]

% Colors
\definecolor{rubricred}{rgb}{0.65,0.08,0.08}

% ✠ (U+2720) fallback via Noto Sans Symbols (Dingbats block)
\newfontface\CrossFont[Path=/usr/share/fonts/truetype/noto/,Scale=MatchLowercase]{NotoSansSymbols-Black.ttf}
\newcommand{\crux}{{\color{rubricred}{\Large\CrossFont\symbol{"2720}}}}

% Rubric (red italic)
\newcommand{\rubric}[1]{{\color{rubricred}\small\itshape #1}}

% Section heading (small caps)
\newcommand{\sectionheading}[1]{%
  \bigskip\noindent{\small\scshape #1}\par\smallskip\noindent%
}

% Psalm mediant marker
\newcommand{\mediant}{\,{\small *}\,}

% Psalm verses environment and command
\newenvironment{psalmverses}{%
  \setlength{\parindent}{0pt}%
  \setlength{\parskip}{2pt}%
}{}

% \psalmverse{num}{text} — num is empty for unnumbered first verse
\newcommand{\psalmverse}[2]{%
  \if\relax\detokenize{#1}\relax%
    \noindent #2\par%
  \else%
    \noindent\hangindent=1.5em\hangafter=1\makebox[1.5em][l]{{\small\textbf{#1}}}#2\par%
  \fi%
}

% Gloria Patri
\newcommand{\gloriapatri}[2]{\noindent #1 \mediant{} #2\par}

% Antiphon
\newcommand{\ant}[1]{\noindent\textit{Ant.}\enspace\textit{#1}\par}

\setlength{\parskip}{4pt}
\setlength{\parindent}{0pt}
\pagestyle{plain}

\begin{document}
`)
	return b.String()
}

// texTitleBlock returns the title block for the hour.
func texTitleBlock(hour *models.OfficeHour) string {
	var b strings.Builder
	b.WriteString("\\begin{center}\n")
	fmt.Fprintf(&b, "  {\\Large\\scshape The Order for %s}\\\\[4pt]\n", escapeTeX(hour.Hour))
	fmt.Fprintf(&b, "  {\\normalsize %s}\\\\[2pt]\n", escapeTeX(hour.Date.Format("Monday, January 2, 2006")))
	if hour.Feast != "" {
		fmt.Fprintf(&b, "  {\\normalsize\\itshape %s}\\\\[2pt]\n", escapeTeX(hour.Feast))
	}
	fmt.Fprintf(&b, "  {\\small\\itshape Season: %s \\quad$\\cdot$\\quad Color: %s}\n",
		escapeTeX(string(hour.Season)), escapeTeX(string(hour.Color)))
	b.WriteString("\\end{center}\n\n")
	b.WriteString("\\bigskip\\hrule\\bigskip\n\n")
	return b.String()
}

// texSection formats a single OfficeSection.
func texSection(section models.OfficeSection, dataDir string, chant bool) string {
	var b strings.Builder

	if section.Label != "" {
		fmt.Fprintf(&b, "\\sectionheading{%s}\n\n", escapeTeX(section.Label))
	}

	for _, elem := range section.Elements {
		b.WriteString(texElement(elem, dataDir, chant))
	}

	return b.String()
}

// texElement dispatches to the appropriate formatter for each element type.
func texElement(elem models.OfficeElement, dataDir string, chant bool) string {
	var b strings.Builder

	switch elem.Type {
	case models.Rubric:
		fmt.Fprintf(&b, "\\rubric{%s}\n\n", escapeTeX(elem.Text))

	case models.Heading:
		fmt.Fprintf(&b, "\\sectionheading{%s}\n\n", escapeTeX(elem.Text))

	case models.Antiphon:
		if elem.Text != "" {
			if strings.Contains(elem.Text, "\n") {
				b.WriteString(formatMultilineAntiphonTeX(elem))
			} else {
				fmt.Fprintf(&b, "\\ant{%s}\n\n", texLine(elem.Text))
			}
		}

	case models.Psalm, models.Canticle:
		if elem.Label != "" {
			fmt.Fprintf(&b, "\n{\\small\\itshape %s}\n\n", escapeTeX(elem.Label))
		}
		b.WriteString(formatPsalmTeX(elem.Text, dataDir, elem.Label, elem.Type, chant))

	case models.Hymn:
		if elem.Label != "" {
			fmt.Fprintf(&b, "\n{\\small\\itshape %s}\n\n", escapeTeX(elem.Label))
		}
		b.WriteString(formatHymnTeX(elem.Text, dataDir, elem.Label, chant))

	case models.PsalmDoxology:
		b.WriteString(formatGloriaPatriTeX(elem.Text))

	case models.Doxology, models.Versicle, models.Response,
		models.Prayer, models.Collect, models.Chapter,
		models.Blessing, models.Preces:
		b.WriteString(formatLiturgicalBlockTeX(elem.Text))
	}

	return b.String()
}

// formatPsalmTeX renders a psalm or canticle element.
// When chant is true, checks for a .gabc file first; falls back to text rendering.
func formatPsalmTeX(text, dataDir, label string, elemType models.ElementType, chant bool) string {
	category := "psalms"
	if elemType == models.Canticle {
		category = "canticles"
	}
	slug := labelToSlug(label, elemType)
	if chant && hasGABC(dataDir, category, slug) {
		return fmt.Sprintf("\\gregorioscore{%s}\n\n", gabcBase(dataDir, category, slug))
	}

	lines := strings.Split(text, "\n")

	// Title block: find first blank line; extract scripture ref if present.
	scriptureRef := ""
	contentStart := len(lines)
	for i, line := range lines {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" {
			contentStart = i + 1
			break
		}
		if strings.HasPrefix(trimmed, "!") {
			scriptureRef = trimmed[1:]
		}
	}

	var b strings.Builder

	if scriptureRef != "" {
		fmt.Fprintf(&b, "{\\small\\itshape %s}\n\n", escapeTeX(scriptureRef))
	}

	b.WriteString("\\begin{psalmverses}\n")

	gloriaOpen := false
	gloriaLine1 := ""

	for _, line := range lines[contentStart:] {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}

		// Section break (canticles)
		if strings.HasPrefix(line, "[section:") && strings.HasSuffix(line, "]") {
			heading := strings.TrimSpace(line[9 : len(line)-1])
			b.WriteString("\\end{psalmverses}\n")
			fmt.Fprintf(&b, "\\sectionheading{%s}\n", escapeTeX(heading))
			b.WriteString("\\begin{psalmverses}\n")
			continue
		}

		// Gloria Patri — two-line rendering
		if strings.HasPrefix(line, "Glory be") {
			gloriaLine1 = texLine(line)
			gloriaOpen = true
			continue
		}
		if gloriaOpen && (strings.HasPrefix(line, "as it was") || strings.HasPrefix(line, "As it was")) {
			fmt.Fprintf(&b, "\\gloriapatri{%s}{%s}\n", gloriaLine1, texLine(line))
			gloriaOpen = false
			gloriaLine1 = ""
			continue
		}

		// Numbered verse detection: "2. text", "10. text", or Benedicite "2 text".
		verseNum, verseText, _ := splitLeadingVerseNumber(line)

		parts := strings.SplitN(verseText, " * ", 2)
		first := texLine(parts[0])

		if len(parts) == 2 {
			second := texLine(parts[1])
			fmt.Fprintf(&b, "\\psalmverse{%s}{%s\\mediant{}%s}\n", verseNum, first, second)
		} else {
			fmt.Fprintf(&b, "\\psalmverse{%s}{%s}\n", verseNum, first)
		}
	}

	if gloriaOpen {
		// Malformed Gloria (missing second line) — emit what we have
		fmt.Fprintf(&b, "\\psalmverse{}{%s}\n", gloriaLine1)
	}

	b.WriteString("\\end{psalmverses}\n\n")
	return b.String()
}

// formatHymnTeX renders a hymn element.
// Hymn text: first line is Latin title, blank line, then stanzas separated by blank lines.
func formatHymnTeX(text, dataDir, label string, chant bool) string {
	slug := labelToSlug(label, models.Hymn)
	if chant && hasGABC(dataDir, "hymns", slug) {
		return fmt.Sprintf("\\gregorioscore{%s}\n\n", gabcBase(dataDir, "hymns", slug))
	}

	lines := strings.Split(text, "\n")

	// First non-blank line is the Latin title; skip it.
	contentStart := 0
	for i, line := range lines {
		if strings.TrimSpace(line) == "" {
			contentStart = i + 1
			break
		}
	}

	var b strings.Builder
	var stanzaLines []string

	flushStanza := func() {
		if len(stanzaLines) == 0 {
			return
		}
		b.WriteString("\\noindent ")
		for i, l := range stanzaLines {
			if i > 0 {
				b.WriteString("\\\\\n")
			}
			b.WriteString(texLine(l))
		}
		b.WriteString("\\par\\smallskip\n")
		stanzaLines = nil
	}

	for _, line := range lines[contentStart:] {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" {
			flushStanza()
		} else {
			stanzaLines = append(stanzaLines, trimmed)
		}
	}
	flushStanza()

	b.WriteString("\n")
	return b.String()
}

// formatMultilineAntiphonTeX renders a multi-line antiphon (e.g., a Marian
// antiphon). The first paragraph is the anthem proper and is set in italics;
// any remainder (versicle, collect) uses the standard liturgical block.
func formatMultilineAntiphonTeX(elem models.OfficeElement) string {
	var b strings.Builder

	if elem.Label != "" {
		fmt.Fprintf(&b, "\n{\\small\\itshape %s}\n\n", escapeTeX(elem.Label))
	}

	anthem, rest, _ := strings.Cut(elem.Text, "\n\n")
	var anthemLines []string
	for line := range strings.SplitSeq(anthem, "\n") {
		if line = strings.TrimSpace(line); line != "" {
			anthemLines = append(anthemLines, texLine(line))
		}
	}
	if len(anthemLines) > 0 {
		fmt.Fprintf(&b, "\\noindent{\\itshape %s}\\par\n", strings.Join(anthemLines, " "))
	}
	if rest = strings.TrimSpace(rest); rest != "" {
		b.WriteString("\\smallskip\n")
		b.WriteString(formatLiturgicalBlockTeX(rest))
	} else {
		b.WriteString("\n")
	}
	return b.String()
}

// formatLiturgicalBlockTeX renders versicles, responses, prayers, chapters,
// blessings, and preces with appropriate LaTeX markup. Consecutive prose
// lines are hard-wrapped sense-lines in the corpus, so they are joined into
// a flowing paragraph; blank lines mark paragraph breaks.
func formatLiturgicalBlockTeX(text string) string {
	lines := strings.Split(text, "\n")
	var b strings.Builder

	var proseLines []string

	flushProse := func() {
		if len(proseLines) == 0 {
			return
		}
		b.WriteString("\\noindent ")
		b.WriteString(strings.Join(proseLines, " "))
		b.WriteString("\\par\n")
		proseLines = nil
	}

	for _, line := range lines {
		line = strings.TrimSpace(line)

		if line == "" {
			flushProse()
			b.WriteString("\\smallskip\n")
			continue
		}

		// Bracket title artifact — skip silently
		if strings.HasPrefix(line, "[") && strings.HasSuffix(line, "]") &&
			strings.Contains(line[1:len(line)-1], " ") {
			continue
		}

		// Scripture reference
		if strings.HasPrefix(line, "!") {
			flushProse()
			fmt.Fprintf(&b, "\\noindent{\\small\\itshape %s}\\par\n", escapeTeX(line[1:]))
			continue
		}

		// Versicle
		if strings.HasPrefix(line, "V. ") {
			flushProse()
			fmt.Fprintf(&b, "\\noindent\\Vbar{}%s\\par\n", texLine(line[3:]))
			continue
		}

		// Response
		if strings.HasPrefix(line, "R. ") {
			flushProse()
			fmt.Fprintf(&b, "\\noindent\\Rbar{}%s\\par\n", texLine(line[3:]))
			continue
		}

		// Blessing sigil
		if strings.HasPrefix(line, "Blessing. ") {
			flushProse()
			fmt.Fprintf(&b, "\\noindent\\textbf{Blessing.}\\kern0.3em{}%s\\par\n", texLine(line[10:]))
			continue
		}

		proseLines = append(proseLines, texLine(line))
	}

	flushProse()
	b.WriteString("\n")
	return b.String()
}

// formatGloriaPatriTeX renders a two-line psalm-doxology (Gloria Patri).
func formatGloriaPatriTeX(text string) string {
	lines := strings.Split(text, "\n")
	var line1, line2 string
	if len(lines) >= 2 {
		line1 = strings.TrimSpace(lines[0])
		line2 = strings.TrimSpace(lines[1])
	} else {
		line1 = strings.TrimSpace(text)
	}
	if line2 != "" {
		return fmt.Sprintf("\\gloriapatri{%s}{%s}\n\n", texLine(line1), texLine(line2))
	}
	return fmt.Sprintf("\\noindent %s\\par\n\n", texLine(line1))
}

// escapeTeX escapes LaTeX special characters in plain text.
// Single-pass rune scanner avoids the ordering problem of chained ReplaceAll calls.
func escapeTeX(s string) string {
	var b strings.Builder
	b.Grow(len(s))
	for _, r := range s {
		switch r {
		case '\\':
			b.WriteString(`\textbackslash{}`)
		case '&':
			b.WriteString(`\&`)
		case '%':
			b.WriteString(`\%`)
		case '$':
			b.WriteString(`\$`)
		case '#':
			b.WriteString(`\#`)
		case '_':
			b.WriteString(`\_`)
		case '{':
			b.WriteString(`\{`)
		case '}':
			b.WriteString(`\}`)
		case '~':
			b.WriteString(`\textasciitilde{}`)
		case '^':
			b.WriteString(`\textasciicircum{}`)
		default:
			b.WriteRune(r)
		}
	}
	return b.String()
}

// texLine escapes LaTeX specials and replaces the ✠ cross with \crux{}.
func texLine(s string) string {
	return strings.ReplaceAll(escapeTeX(s), "✠", `\crux{}`)
}

// GABC helpers

// gabcPath returns the full path to a .gabc file (for existence checks).
func gabcPath(dataDir, category, slug string) string {
	return filepath.Join(dataDir, "texts", "chant", category, slug+".gabc")
}

// gabcBase returns the path without the .gabc extension, as required by \gregorioscore.
// Gregoriotex appends .gabc (and .gtex) itself.
func gabcBase(dataDir, category, slug string) string {
	return filepath.Join(dataDir, "texts", "chant", category, slug)
}

func hasGABC(dataDir, category, slug string) bool {
	if dataDir == "" || slug == "" {
		return false
	}
	_, err := os.Stat(gabcPath(dataDir, category, slug))
	return err == nil
}

// labelToSlug converts an element label to a filesystem slug for GABC lookup.
//   - Psalm "Psalm 67" → "067"
//   - Psalm "Psalm 118" → "118"
//   - Canticle "Benedictus" → "benedictus"
//   - Hymn "Aeterne Rerum Conditor" → "aeterne-rerum-conditor"
func labelToSlug(label string, elemType models.ElementType) string {
	if label == "" {
		return ""
	}
	switch elemType {
	case models.Psalm:
		// "Psalm N" → zero-padded 3-digit string
		after, ok := strings.CutPrefix(label, "Psalm ")
		if !ok {
			return slugify(label)
		}
		// Strip sub-section like "118 (Aleph)" → "118"
		num := strings.Fields(after)[0]
		if len(num) < 3 {
			num = strings.Repeat("0", 3-len(num)) + num
		}
		return num
	default:
		return slugify(label)
	}
}

// slugify converts a string to a lowercase hyphen-separated slug.
func slugify(s string) string {
	s = strings.ToLower(s)
	var b strings.Builder
	prevWasSep := false
	for _, r := range s {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			b.WriteRune(r)
			prevWasSep = false
		} else if !prevWasSep && b.Len() > 0 {
			b.WriteRune('-')
			prevWasSep = true
		}
	}
	return strings.TrimRight(b.String(), "-")
}

// allDigits reports whether s consists entirely of ASCII digits.
func allDigits(s string) bool {
	if s == "" {
		return false
	}
	for _, c := range s {
		if c < '0' || c > '9' {
			return false
		}
	}
	return true
}

// splitLeadingVerseNumber peels a leading verse number from a psalm or canticle
// line. Accepts "2. Text" and Benedicite-style "2 Text". Numbers are at most 3 digits.
func splitLeadingVerseNumber(line string) (num, rest string, ok bool) {
	i := 0
	for i < len(line) && line[i] >= '0' && line[i] <= '9' {
		i++
	}
	if i == 0 || i > 3 {
		return "", line, false
	}
	switch {
	case i+1 < len(line) && line[i] == '.' && line[i+1] == ' ':
		return line[:i], strings.TrimSpace(line[i+2:]), true
	case i < len(line) && line[i] == ' ':
		return line[:i], strings.TrimSpace(line[i+1:]), true
	default:
		return "", line, false
	}
}
