#!/usr/bin/env python3
"""Check or regenerate the committed CLI snapshots using the Rust executable.

The existing filenames select hour/date cases. Source-based assertions live
separately in the Rust test suite and are never regenerated by this tool.
"""
import argparse
import difflib
import json
from pathlib import Path
import re
import subprocess
import sys

ROOT = Path(__file__).resolve().parent.parent
GOLDEN = ROOT / "tests/fixtures/golden"
OFFICE = ROOT / "target/release/office"


def render(path):
    name = path.name
    if match := re.fullmatch(r"(lauds|prime|terce|sext|none|vespers|compline)-(\d{4}-\d{2}-\d{2})\.txt", name):
        args = list(match.groups())
    elif match := re.fullmatch(r"ordo-(\d{4})\.txt", name):
        args = ["ordo", match[1]]
    elif name == "audit-report.txt":
        args = ["audit", "-year", "2026"]
    elif name == "assurance-report.md":
        args = ["review", "assurance", "-markdown"]
    elif name == "parity-snapshot.json":
        baseline = json.loads((ROOT / "data/review/assurance-baseline.json").read_text())
        args = ["dump", "-start", str(baseline["start_year"]), "-years", str(baseline["years"]), "-digest"]
    else:
        raise ValueError(f"unrecognized golden: {name}")
    output = subprocess.check_output([str(OFFICE), *args], cwd=ROOT)
    if name == "audit-report.txt":
        # The audit golden covers the corpus inventory. The CLI additionally
        # prints a calendar sweep, which has separate composition assertions.
        inventory, marker, _ = output.partition(b"=== Sweep 2026:")
        if not marker:
            raise ValueError("audit output is missing its sweep boundary")
        return inventory
    return output


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="compare without modifying files")
    parser.add_argument("--quick", action="store_true", help="omit the full 28-year digest")
    args = parser.parse_args()
    paths = sorted(GOLDEN.iterdir())
    if len(paths) < 100:
        raise RuntimeError("missing golden fixtures")
    mismatches = []
    for path in paths:
        if args.quick and path.name == "parity-snapshot.json":
            continue
        result = render(path)
        if args.check:
            expected = path.read_bytes()
            if expected != result:
                mismatches.append(path.name)
                diff = difflib.unified_diff(expected.decode().splitlines(True), result.decode().splitlines(True),
                                            fromfile=str(path.relative_to(ROOT)), tofile="generated")
                sys.stderr.write("".join(diff)[:20000])
        else:
            # Only replace a golden after the entire command succeeds.
            path.write_bytes(result)
        print(f"{'checked' if args.check else 'updated'} {path.name}", flush=True)
    if mismatches:
        sys.exit("Golden mismatches: " + ", ".join(mismatches) + ". Review the changes before running make golden.")


if __name__ == "__main__":
    main()
